### ISSUE TITLE
Make JHove available to Maven Central

### ISSUE THREAD

**Issue by Abdull** [openpreserve/jhove#102]
The README.md says "_The 1.14 release artifacts will be published to Maven central_", but I couldn't find them there.

**Comment by tledoux** [comment]
+1 (important to spread the use)

**Comment by pmay** [comment]
+1

**Comment by chhkb** [comment]
Christen, KBDB +1

**Comment by friesey** [comment]
Yvonne Tunnat Goportis +1

**Comment by carlwilson** [comment]
No time to do this on the Hack Day as coordinating and testing took priority, returning to the 1.16 fold.

**Comment by carlwilson** [comment]
Have just successfully deployed v1.16.5 of JHOVE to Maven central: http://repo1.maven.org/maven2/org/openpreservation/jhove/jhove/1.16.5/
