### ISSUE TITLE
Whitespace in name of target file

### ISSUE THREAD

**Issue by trebunski** [openpreserve/jhove#103]
Is there a way to work on files with witespace(s)?
e.g. on Linux 

``` bash
touch 'test file.zip'
jhove test\ file.zip # or even jhove 'test file.zip', I tried it in many different ways 
```

The output from jhove is (it thinks I pass 2 files):

```
Jhove (Rel. 1.15.0-SNAPSHOT, 2016-08-29)
 Date: 2016-08-29 13:11:25 CEST
 RepresentationInformation: test\
  Status: Not well-formed
  ErrorMessage: file not found
 RepresentationInformation: file.zip
  Status: Not well-formed
  ErrorMessage: file not found
```

The only way it worked for me was to use wildcard

``` bash
jhove 'test*file.zip' 
```

Then I get the Output: 

``` bash
Jhove (Rel. 1.15.0-SNAPSHOT, 2016-08-29)
 Date: 2016-08-29 13:11:44 CEST
 RepresentationInformation: test file.zip
  ReportingModule: BYTESTREAM, Rel. 1.3 (2007-04-10)
  LastModified: 2016-08-29 13:08:11 CEST
  Size: 0
  Format: bytestream
  Status: Well-Formed and valid
  SignatureMatches:
   WARC-kb
   GZIP-kb
  InfoMessage: Zero-length file
  MIMEtype: application/octet-stream

```

BUT THAT IS TO DIRTY !!!

Is it possible to repair it, or is there another useable way to utilize jhove without such problems?

**Comment by carlwilson** [comment]
Hi @trebunski 

I'm keen to address this and ensure that JHOVE does something sensible here and intend to do some testing / fixing for the upcoming 1.16 release. Could you give me a few more details about the distro and version you're using.

Thanks

**Comment by trebunski** [comment]
Hi @carlwilson , some information you asked about:
OS

``` bash
more /etc/issue
CentOS release 6.8 (Final)
Kernel \r on an \m
```

Java

``` bash
Java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

Bash

``` bash
bash -version
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Thank you for your interest

**Comment by smmorrissey** [comment]
Sheila +1

**Comment by trebunski** [comment]
Hey @carlwilson
Do You have any date/time Information about upcoming 1.16 release. 
When is it (public) available?

Thanks

**Comment by carlwilson** [comment]
Hi @trebunski the new release is planned for sometime in November. Development builds with features and fixes will start to appear in October, they are available within a few minutes of updates to `integration` from the OPF's build server: http://software.openpreservation.org/dev/. The development builds for 1.16 will be versioned 1.15 up to the release.

**Comment by david-russo** [comment]
I'm seeing a similar problem in Windows' command prompt:

```
C:\jhove>jhove "New Text Document.txt"
Text was unexpected at this time.
```

JHOVE 1.15.0-SNAPSHOT, Windows 7 (64-bit), JRE 1.8.0_102
