### ISSUE TITLE
Enhance JHOVE's checksumming capabilities

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#104]
## Dev Effort
1D

See PR: #386 

## Description
The digest algorithms currently supported by JHOVE are:
- CRC32
- MD5
- SHA1

Java provides native support for these additional algorithms:
- SHA256
- SHA384
- SHA512

These could be added quite easily but this would also require a change to JHOVE's config to allow the user to select the algorithms they wanted to use.

**Comment by chhkb** [comment]
Christen, KBDB +1
