### ISSUE TITLE
XMLHandler outputs wrong bitPerSample in MIX

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#108]
While using XMLHandler, JHOVE creates incorrect number (2) of mix:bitsPerSampleValue MIX tags:

```
<mix:ImageColorEncoding>
  <mix:BitsPerSample>
    <mix:bitsPerSampleValue>8</mix:bitsPerSampleValue>
    <mix:bitsPerSampleValue>8</mix:bitsPerSampleValue>
    <mix:bitsPerSampleUnit>integer</mix:bitsPerSampleUnit>
  </mix:BitsPerSample>
  <mix:samplesPerPixel>3</mix:samplesPerPixel>
</mix:ImageColorEncoding>
```

The attached patch fixes iteration over the array of bitsPerSampleValue starting from 0. The accompanying patch is available from SourceForge: [https://sourceforge.net/p/jhove/patches/_discuss/thread/5d7c7155/77d4/attachment/XmlHandler.patch](https://sourceforge.net/p/jhove/patches/_discuss/thread/5d7c7155/77d4/attachment/XmlHandler.patch)

**Comment by carlwilson** [comment]
The accompanying patch is available from SourceForge: [https://sourceforge.net/p/jhove/patches/_discuss/thread/5d7c7155/77d4/attachment/XmlHandler.patch](https://sourceforge.net/p/jhove/patches/_discuss/thread/5d7c7155/77d4/attachment/XmlHandler.patch)

**Comment by tledoux** [comment]
This patch has been applied in commit 24487723ac39a312b182a086cef9223ebcb36027.

Closing #108

**Comment by tledoux** [comment]
As stated before. Closed

**Comment by carlwilson** [comment]
Nice, thanks @tledoux
