### ISSUE TITLE
Problem with PDF annotation dictionaries

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#113]
A file from the Open Planets Foundation format corpus, simple-annotated-in-adobe-x.pdf, is reported as well-formed but not valid, with the not very informative message "Invalid annotations." Setting breakpoints reveals that where an array is expected for the "Annots" array of annotation dictionaries, a keyword is being found instead. I can't immediately figure out why this is. Even if it's not in accordance with the spec, it's an Adobe-generated file.

Further comment from @gmcgath :

> File from format corpus:
> [simple-annotated-in-adobe-x.pdf](https://github.com/openpreserve/jhove/files/458892/simple-annotated-in-adobe-x.pdf)

and again from @gmcgath 

> A similar problem exists in the same file with the "Names" dictionary. This looks like an underlying feature of PDF that I've overlooked.

and again from @gmcgath 22-05-2013

> I've posted a question at http://superuser.com/questions/589207/can-a-keyword-be-in-a-pdf-annots-array to see if anyone can explain what's going on. So far there have been no answers.

**Comment by david-russo** [comment]
JHOVE 1.16.7 reports this file as "Well-formed and valid". The annotation appears to be in a compressed stream object, so it may have been affected by #151.
