### ISSUE TITLE
Empty message body in the validation error

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#114]
While processing this PDF with JHOVE, http://www.fcla.edu/daitss-test/files/Zheng_Liping_200512_PHD.pdf. An error occurs with a status of "Well-Formed, but not valid"

```
<size>3649429</size>
<format>PDF</format>
<version>1.5</version>
<status>Well-Formed, but not valid</status>
<sigMatch>
  <module>PDF-hul</module>
</sigMatch>
<messages>
  <message offset="2098097" severity="error"></message>
 <message offset="2098153" severity="error"></message>
</messages>
```

Shouldn't there be a message body indicating what is validation error?

@gmcgath 02-06-2013:

> I've checked in a new version of PdfModule.java that fixes the problem. addDestination was failing to check whether it could safely get a page object number, and throwing a NullPointerException when it couldn't. The handler was assuming there would be a message string in the exception. I've fixed it on both of these points. For now it can be built with the updated source code; it should be fixed in JHOVE 1.10, whenever that happens.

**Comment by david-russo** [comment]
JHOVE 1.16.7 reports this file as "Well-formed and valid" with no other messages.
