### ISSUE TITLE
add Audit handler output explanation to documentation.

### ISSUE THREAD

**Issue by comstock** [openpreserve/jhove#121]
Suggesting someone write an explanation of the output from the **Audit handler** and add it to the **documentation**.

**Comment by comstock** [comment]
Could someone (best regards, @gmcgath) post a brief explanation of how to read the audit summaries?

What is the significance of the **numbers in parentheses**, and to **following plus-sign and numbers**?

#### Examples from summaries

```/DNG sample images for testing/.rawstudio: 18 (8,10) + 0,0```

```image/tiff: 24 (16,8)```

**Comment by marhop** [comment]
Hi @comstock, the audit handler is documented at <http://jhove.openpreservation.org/getting-started/#audit>, although it's missing an explanation of the numbers yet. I added a [pull request](https://github.com/openpreserve/jhove/pull/311) to remedy that. In short terms:

  * MIME summary: `number of files (number of valid files, number of well-formed files)`
  * directory summary: `number of files (number of valid files, number of well-formed files) + number of files that were not processed, number of files that were not found`

Just in case you are curious: I got the info from [this file](https://github.com/openpreserve/jhove/blob/integration/jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/AuditHandler.java).

**Comment by comstock** [comment]
@marhop, many thanks. This is helpful.

I wonder how it reports invalid, non-conforming files? Guessing:

"image/tiff: 30 (20,0) + 0,0" would mean that 20 of 30 files identified as TIFF conformed to the TIFF specification and 10 were mal-formed?

Again, thanks.

-- Bill

**Comment by marhop** [comment]
Yes, I think that's how it would look like.
