### ISSUE TITLE
Broken website links

### ISSUE THREAD

**Issue by david-russo** [openpreserve/jhove#122]
http://jhove.openpreservation.org/documentation/
- The JavaDocs link under _JHOVE API_.
- The _JHOVE2_ links.

http://jhove.openpreservation.org/modules/pdf/
- All but the first three PDF reference links.

http://jhove.openpreservation.org/documentation/dev-module/
- The first link on this page... and probably the rest.
- Needs some general formatting love...

**Comment by carlwilson** [comment]
Have fixed broken links and added htmlproof checking to gh-pages build to ensure that none are introduced going forward and we're warned if resources disappear.
