### ISSUE TITLE
Add or improve PDF module error explanations in spreadsheet

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#131]
This [GoogleDocs spreadsheet](https://docs.google.com/spreadsheets/d/1zyg4eqH6akoehI10fNhzroaW3CgcwUjkNlvvVZvFDyo) details all of the PDF Hul Module error messages. One of the things we want to do with this list is to add better explanations of the error's real meaning in Column D, labelled "Explanation".

There's plenty of gaps and the entries that are there require review. If you can improve the information here it will eventually be included in a JHOVE release with improved error messaging, or on the JHOVE Error Wiki we're creating.

You can add text or links to the spread sheet for now, results from the Hack Day will be collated in the days after the event.

**Comment by andreakb** [comment]
Added a few explanations with links to the documentation.

**Comment by carlwilson** [comment]
Again, this can be closed as the spreadsheet is now ebedded in code.
