### ISSUE TITLE
Externalise PNG validation error messages.

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#134]
## Dev Effort
1D

## Description
In order to improve the way that JHOVE reports validation errors we first need move the error messages into a single place. This has currently been done [here for the PDF Module](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java). The work is a little painful, but necessary if we're to improve JHOVE's reporting.

The comments at the [top of the PDF Constants file](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java#L7). Please talk to @carlwilson if you need more guidance.

**Comment by ross-spencer** [comment]
Second sheet on the JHOVE errors list: https://docs.google.com/spreadsheets/d/1zyg4eqH6akoehI10fNhzroaW3CgcwUjkNlvvVZvFDyo/edit?ts=57fa9854#gid=450964881

**Comment by ross-spencer** [comment]
Thus far, 66 strings have been extracted with source code links form each of the PNG modules. 

_Type, Explanation, Examples, Impact, Cure, Classification_ still need filling in at time of writing.

**Comment by carlwilson** [comment]
Thanks for this, I'll take a look at the module and see what I can do about externalising these in the code a little later today.

**Comment by samalloing** [comment]
I updated this, filled in the type column and added the Constant column

**Comment by carlwilson** [comment]
Hi @samalloing and @jacobtakema. I've now assigned this issue to you. To see how this works in practise you can take a look at any of the main JHOVE modules. The [ASCII module](https://github.com/openpreserve/jhove/tree/integration/jhove-modules/ascii-hul) is a good example. The error messages and assigned ID's are held in a resource file, the [ASCII one is here](https://github.com/openpreserve/jhove/blob/integration/jhove-modules/ascii-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/ascii/ErrorMessages.properties). It's short as there aren't many ASCII module messages. There's an ID and message for each error.

There's then a message constant class that loads up the resource errors, the [ASCII one is here](https://github.com/openpreserve/jhove/blob/integration/jhove-modules/ascii-hul/src/main/java/edu/harvard/hul/ois/jhove/module/ascii/MessageConstants.java). This means that there's genuine constants for messages, and if there are any mistakes in IDs they'll be picked up when JHOVE's run, and by basic testing.

Finally, to raise the appropriate error see this example: https://github.com/openpreserve/jhove/blob/integration/jhove-modules/ascii-hul/src/main/java/edu/harvard/hul/ois/jhove/module/AsciiModule.java#L159

Any questions just raise them here, good luck.
