### ISSUE TITLE
Externalise AIFF validation error messages

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#135]
In order to improve the way that JHOVE reports validation errors we first need move the error messages into a single place. This has currently been done [here for the PDF Module](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java). The work is a little painful, but necessary if we're to improve JHOVE's reporting.

The comments at the [top of the PDF Constants file](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java#L7). Please talk to @carlwilson if you need more guidance.

**Comment by andreakb** [comment]
@carlwilson I can take this one on if you can send me some instructions. Thanks!

**Comment by carlwilson** [comment]
Hi @andreakb I'm just looking to see whether I may have done it, I'll be another 30 minutes or so, a couple of things on right now sorry.

**Comment by andreakb** [comment]
No worries, @carlwilson let me know if there's any of these I can help you out on!
