### ISSUE TITLE
Externalise HTML Module validation error messages

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#138]
In order to improve the way that JHOVE reports validation errors we first need move the error messages into a single place. This has currently been done [here for the PDF Module](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java). The work is a little painful, but necessary if we're to improve JHOVE's reporting.

The comments at the [top of the PDF Constants file](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java#L7). Please talk to @carlwilson if you need more guidance.

**Comment by tledoux** [comment]
Taking this one too for externalising messages

**Comment by ross-spencer** [comment]
@kfrn and I have added line references to the sheet. 

Presumption is that all the HTML error strings have been found now.
