### ISSUE TITLE
Externalise JPEG 2000 Module validation error messages

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#140]
In order to improve the way that JHOVE reports validation errors we first need move the error messages into a single place. This has currently been done [here for the PDF Module](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java). The work is a little painful, but necessary if we're to improve JHOVE's reporting.

The comments at the [top of the PDF Constants file](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java#L7). Please talk to @carlwilson if you need more guidance.

**Comment by marhop** [comment]
I'll see to this one during the spring 2017 online hack day.

**Comment by carlwilson** [comment]
@marhop your wish is our command, thanks very much. I've invited you as a collaborator, for now, accept and I'll assign you the issue.

**Comment by marhop** [comment]
The code is in PR #239, and I listed all messages in the spreadsheet:
https://docs.google.com/spreadsheets/d/1zyg4eqH6akoehI10fNhzroaW3CgcwUjkNlvvVZvFDyo/edit?ts=57fa9854#gid=1877319402
