### ISSUE TITLE
Externalise XML module validation error messages

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#144]
In order to improve the way that JHOVE reports validation errors we first need move the error messages into a single place. This has currently been done [here for the PDF Module](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java). The work is a little painful, but necessary if we're to improve JHOVE's reporting.

The comments at the [top of the PDF Constants file](https://github.com/openpreserve/jhove/blob/exp-message-constants/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java#L7). Please talk to @carlwilson if you need more guidance.

**Comment by tledoux** [comment]
I will take this one with UTF-8...

**Comment by kfrn** [comment]
@ross-spencer and I just looked through the XML module, we think all of the error messages are accounted for. We have added line references for the three error/warning messages.
Logged in this spreadsheet: https://docs.google.com/spreadsheets/d/1zyg4eqH6akoehI10fNhzroaW3CgcwUjkNlvvVZvFDyo/edit?ts=57fa9854#gid=698461340
