### ISSUE TITLE
Add better external reference information to JHOVE website.

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#145]
## Dev Effort
2D

## Description
There must be better documentation for some of the formats currently handled by JHOVE modules. Finding links to authoritative documentation, e.g. specifications, or good, preferably non-technical, online primers and adding links and brief descriptions to the JHOVE website would help new users.

**Comment by andreakb** [comment]
Creating a google doc for PDF stuff first, I will add it to the issue in github once it's fleshed out a bit.
edit: link to google doc is [here](https://docs.google.com/document/d/1CWGFkiCt_mnY3zUuNNmCohgSclzrrtFn4zN5VRLLOhI/edit?usp=sharing)

**Comment by carlwilson** [comment]
Thanks @andreakb I can see the information, expect a website addition a little later this week, I'll close this issue when it's added and put the link in so you can see it.
