### ISSUE TITLE
PNG throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#148]
## Dev Effort
TBC

## Description
Null pointer making module return Not Well Formed and Valid: 

```
  JhoveView (Rel. 1.14.6, 2016-05-12)
   Date: 2016-10-11 12:19:58 NZDT
   RepresentationInformation: \\arcwn-fp02.archives.net\homefolders$\spencero\Desktop\tiger.png
    ReportingModule: PNG-gdm, Rel. 1.0 (2016-02-25)
    LastModified: 2016-08-03 10:17:49 NZST
    Size: 1249947
    Format: PNG
    Status: Not well-formed
    ErrorMessage: Exception java.lang.NullPointerException
    MIMEtype: image/png
    Blue background value: 255
    Green background value: 255
    Pixel unit: Metre
    Red background value: 255
    X pixels per unit: 2835
    Y pixels per unit: 2835
```

PNG Attached: 

![tiger](https://cloud.githubusercontent.com/assets/1880412/19254109/ecf54504-8fac-11e6-8d0f-69b2e83e6c77.png)

**Comment by marcwer** [comment]
I'm having the same problem validating png-files with PNG-gdm.

**Comment by gmcgath** [comment]
I'll take a look at this one.

**Comment by carlwilson** [comment]
@ross-spencer there's now a fix for this supplied by @karenhanson at #580. We're curious if the file above is OK to distribute with the source for use in unit tests, please?

**Comment by ross-spencer** [comment]
Gosh! There's a throwback.

I think we'd need to ask the folks at Florida Keys Community College Library: https://www.flickr.com/photos/fkcclibrary/7605201004/ 

I can follow up on that one.

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PNG throws java.lang.NullPointerException #148 - Assigned to Karen Hanson](https://trello.com/c/TduhDP8Y/10-png-throws-javalangnullpointerexception-148-assigned-to-karen-hanson)

**Comment by carlwilson** [comment]
Thanks very much @ross-spencer, I'm loving the throwback nature of a lot of what's going on here. Nothing like shifting a bug that's been on the list for years to feel better :)

**Comment by ross-spencer** [comment]
I have emailed FKCC, will keep folks posted! :crossed_fingers:

**Comment by karenhanson** [comment]
I've found an alternative test file to use for this - just pushed the change to the PR.
