### ISSUE TITLE
TODO noted in PNG module: Incomplete Error Reporting?

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#149]
https://github.com/openpreserve/jhove/blob/integration/jhove-modules/src/main/java/com/mcgath/jhove/module/png/IhdrChunk.java#L179

**Comment by gmcgath** [comment]
Has anyone looked at my pull request on this? I wasn't in a position to test it very thoroughly, so it should be verified before incorporating (of course).

**Comment by carlwilson** [comment]
Hi Gary, I'd seen it but we'd already set the milestone for 1.16 when this came in. I'm going to look to get this merged into 1.17 development early on so it will make the 1.18 release. If all goes to plan that won't be a year away.
