### ISSUE TITLE
Add a "Get JHOVE" button to main JHOVE webpage

### ISSUE THREAD

**Issue by pmay** [openpreserve/jhove#168]
It would be handy to have a button on the main jhove page that lets you download the installer directly, rather than taking you to another page where the actual download link is small.

(Currently: "Download JHOVE" on http://jhove.openpreservation.org/ takes you to another page http://jhove.openpreservation.org/getting-started#download)

**Comment by carlwilson** [comment]
The button on the home page now does what it says on the tin.
