### ISSUE TITLE
Support needed for RF64-formatted WAVs

### ISSUE THREAD

**Issue by pmay** [openpreserve/jhove#184]
Example (although can't share the wav file):
```
>java -jar jhove-apps-1.15.0-SNAPSHOT.jar -m WAVE-hul c:\Data\WAVs\Larger_than_2GB_RF64.wav
Jhove (Rel. 1.15.0-SNAPSHOT, 2016-12-02)
 Date: 2017-01-10 16:06:17 GMT
 RepresentationInformation: c:\Data\WAVs\Larger_than_2GB_RF64.wav
  ReportingModule: WAVE-hul, Rel. 1.3 (2007-12-14)
  LastModified: 2014-04-04 03:01:35 BST
  Size: 3371107136
  Format: WAVE
  Status: Not well-formed
  ErrorMessage: Document does not start with RIFF chunk
   Offset: 0
  MIMEtype: audio/x-wave
```

**Comment by vzakuta** [comment]
Same here, at Harvard. We are running into the same issue with WAV files that are over 2 GB.  It would be great if the JHOVE WAVE module was updated to support RF64-formatted WAVs.

Here's my JHOVE output:
Jhove (Rel. 1.14.6, 2016-05-12)
 Date: 2017-02-07 16:26:42 EST
 RepresentationInformation: /Volumes/nas.drs-test-data.data/FITS_Test_Files/AudioInfo_failures/000603031_AT_0001.wav
  ReportingModule: WAVE-hul, Rel. 1.3 (2007-12-14)
  LastModified: 2017-01-19 13:18:41 EST
  Size: 2351006108
  Format: WAVE
  Status: Not well-formed
  SignatureMatches:
   WAVE-hul
  ErrorMessage: Invalid character in Chunk ID: Character = 0x03
   Offset: 131075
  MIMEtype: audio/x-wave
  Profile: PCMWAVEFORMAT

**Comment by david-russo** [comment]
Hi @vzakuta, you seem to be experiencing issue #167 instead, which, if the stars align, could be fixed in the next release.

**Comment by vzakuta** [comment]
Thanks sounds great - thanks @david-russo !
