### ISSUE TITLE
OCR 1.6 pdf isn't well-formed in jhove

### ISSUE THREAD

**Issue by andreakb** [openpreserve/jhove#187]
## Dev Effort
1D

## Description
I'm using jhove version 1.14.6 in debian. I have a scanned PDF (version 1.6) that is well-formed and valid when I run it through jhove. However, when the open the file up in adobe acrobat x pro to OCR the document, and save it, the newly created pdf is no longer valid, and has the error 'invalid page tree node'. I'm attaching both documents.  I wish I could be more useful about what I think the problem is, but to be honest, I'm having a hard time parsing the pdf 1.6 myself, even while I'm looking at adobe's documentation. I'm used to looking at 1.4 and I can't wrap my head around how objects are stored without an xref table? If I'm wrong about that, please let me know. I've tried OCR in different versions of adobe acrobat pro, and they come up with the same result. I don't think an adobe product would create a pdf that's not well-formed, but I could be wrong. The test-Frech is the original scanned document, and the ocrtest is the OCR'd document.  

Thanks so much!
[ocrtest-Frech1976.pdf](https://github.com/openpreserve/jhove/files/733014/ocrtest-Frech1976.pdf)
[test-Frech1976.pdf](https://github.com/openpreserve/jhove/files/733015/test-Frech1976.pdf)

**Comment by carlwilson** [comment]
Have tested both of these files against the 1.23 version soon to be 1.24 and these are now well-formed and valid. There's been a lot of work on the PDF module and it appears that this is now fixed so am closing.
