### ISSUE TITLE
JHOVE returns ErrorMessage: Unexpected end of file on WAV files

### ISSUE THREAD

**Issue by vzakuta** [openpreserve/jhove#193]
JHOVE 1.16 returns the error
ErrorMessage: Unexpected end of file
on all the wav files I tried so far both files over 2 GB and under 2 GB.

Here is a sample message:
ReportingModule: WAVE-hul, Rel. 1.4 (2017-03-14)
  LastModified: 2016-05-19 18:21:38 EDT
  Size: 49926728
  Format: WAVE
  Status: Not well-formed
  SignatureMatches:
   WAVE-hul
  ErrorMessage: Unexpected end of file
   Offset: 50057144
  MIMEtype: audio/x-wave

Can't attach any files as they are over the GitHub limit of 10 mb

JHOVE 1.14 works correctly on WAV files under 2GB but finds WAV files over 2 GB not well formed 
 ReportingModule: WAVE-hul, Rel. 1.3 (2007-12-14)
  LastModified: 2017-01-19 13:18:41 EST
  Size: 2351006108
  Format: WAVE
  Status: Not well-formed
  SignatureMatches:
   WAVE-hul
  ErrorMessage: Invalid character in Chunk ID: Character = 0x03
   Offset: 131075
  MIMEtype: audio/x-wave
  Profile: PCMWAVEFORMAT

**Comment by david-russo** [comment]
Might you be able to share a link to an example file from Google Drive or Dropbox?

**Comment by vzakuta** [comment]
Hi David,
Sure thing.
I uploaded several WAVs here:
https://drive.google.com/drive/folders/0Bz4J5tiwltUzY1lFaEdhXzJySVE?usp=sharing

Thanks
Vitaly

**Comment by daveneiman** [comment]
Here some more information when running the unit test, WaveModuleTest.java and using one of our own valid WAVE files. We put an e.printStackTrace() in WaveModule, line 317  (inside the catch EOFException block).

java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at edu.harvard.hul.ois.jhove.ModuleBase.readUnsignedByte(ModuleBase.java:909)
	at edu.harvard.hul.ois.jhove.module.iff.ChunkHeader.readHeader(ChunkHeader.java:46)
	at edu.harvard.hul.ois.jhove.module.WaveModule.readChunk(WaveModule.java:663)
	at edu.harvard.hul.ois.jhove.module.WaveModule.parse(WaveModule.java:312)
	at edu.harvard.hul.ois.jhove.module.WaveModuleTest.testSample3(WaveModuleTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)

**Comment by david-russo** [comment]
This issue has been fixed for the next release, which should be coming along shortly.

**Comment by vzakuta** [comment]
That’s great news – thanks!
Vitaly

**Comment by carlwilson** [comment]
The fixed version of 1.16 of this is now built and can be downloaded. I've also added some WAV files to the test set, which would have picked this up in the first place. The new version is 1.16.5 (Jenkins burnt a few revision number for me). Thanks very much for spotting and reporting.

**Comment by vzakuta** [comment]
Thank you and sure thing.
We’ll give it a try.
Vitaly

**Comment by daveneiman** [comment]
FYI - Looks like the version in the POM file is still 1.16.0, not 1.16.5 unless I missed something.
<version>1.16.0</version>
Thus, the JAR files in target/ reflect the old version number.

**Comment by carlwilson** [comment]
We don't version the code with the revision numbers as it can become problematic with continuous release policies. Instead, we use a signed Git tag, in this case: https://github.com/openpreserve/jhove/releases/tag/v1.16.5 and allow the [Jenkins build server](http://jenkins.openpreservation.org/job/jhove-v1.16/) to handle the revision versioning. The built jars, JavaDoc jars and source jars (with correct versions) are also signed and added to our artifactory instance, e.g. http://artifactory.openpreservation.org/artifactory/opf-dev/org/openpreservation/jhove/jhove-modules/1.16.5/

IF you want to build a particular version, say 1.16.5 yourself then simply:

    git fetch origin
    git checkout -b a-version v1.16.5
    mvn versions:set -DnewVersion=v1.16.5
    mvn clean install
