### ISSUE TITLE
Remove empty function

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#230]
Spotted by @kfrn and myself, remove the function here, it does nothing! 

https://github.com/openpreserve/jhove/blob/integration/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/xml/XmlDeclHandler.java#L38 

another:

https://github.com/openpreserve/jhove/blob/integration/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/xml/XmlDeclHandler.java#L73

(A good string to search for is 'do nothing' across the repo)

**Comment by kfrn** [comment]
Another: 
https://github.com/openpreserve/jhove/blob/08baeef92fff3c15551c17c71f614089f1bed4bc/jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/JhoveWindow.java#L746

Edit: removed mentions of intentionally empty functions in `XmlLexicalHandler.java` (for error handling)

**Comment by tledoux** [comment]
Those methods are usually needed in order to implement an interface.
For example the method dragOver() is required by the [DropTargetListener](https://docs.oracle.com/javase/7/docs/api/java/awt/dnd/DropTargetListener.html) interface

**Comment by carlwilson** [comment]
The, for our purposes, definitive answer to unused code questions can be found [on Codacy](https://www.codacy.com/app/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJVbnVzZWQgQ29kZSJdfV0=). There's plenty of unused code but it's not complaining about these particular issues. @tledoux makes a good point about required interface methods, though this is sometimes a symptom of design issues.
