### ISSUE TITLE
MP3 module download is broken

### ISSUE THREAD

**Issue by pmay** [openpreserve/jhove#254]
## Dev Effort
0.5D

## Description
The download link from http://jhove.openpreservation.org/modules/third-party/mp3/ gives a 404.

Download button points to: http://jhove.openpreservation.org/modules/third-party/mp3/download/Mp3Module.jar?download=Download

As does the Javadoc button: http://jhove.openpreservation.org/modules/third-party/mp3/javadoc/Mp3ModuleDoc.zip?download=Download+Javadoc+%28Zip%29

**Comment by carlwilson** [comment]
Javadoc was lost forever but the MP3 and ZIP modules are now restored.
