### ISSUE TITLE
Improperly formed date () when () is a valid literal

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#267]
## Dev Effort
0.5D - investigation

## Description
A question, but maybe a bug. We've some documents with blank dates. E.g. 

     /CreationDate ()

From:

     obj.<<./Type /Catalog./Pages 3 0 R.>>.endobj.6 0 obj.<<./Creator (HP Digital Sending Device)./CreationDate ()./Author ()./Producer (HP Digital Sending Device)./Title ()./Subject().>>.endobj         

In PDF-hul 1.9, JHOVE 1.16.7:

     Status: Well-Formed, but not valid
     ErrorMessage: Improperly formed date

While dates are supposed to take a certain format (P100/120):

      D:YYYYMMDDHHmmSSOHH'mm'

Are they not also literals for which the valid options are (P30/49):

      The following are valid literal strings:
         (This is a string)
         (Strings may contain newlines
         and such.)
         (Strings may contain balanced parentheses ( ) and
         special characters (*!&}^% and so on).)
         (The following is an empty string.)
         ()
         (It has zero (0) length.)

Reference: http://www.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf

**Comment by anjackson** [comment]
Table 9.2 "Entries in the document information dictionary" on page 576 of that spec. clearly states `CreationDate` is optional. Presumably the 'right way' to do it is to omit mentioning the `CreationDate` at all rather than declare it but leave it empty, but as you say @ross-spencer the literal is allowed to be empty so that seems to be reasonable interpretation of the spec.

**Comment by thorsted** [comment]
I also have seen a few PDF's with empty date fields which throw an error, one I wanted to add has an additional field for reference:

`<</Author()/CreationDate()/CreationDate--Text()/Creator()/ModDate(D:20170426154048-06'00')/Producer()/Subject()/Title()>>`
