### ISSUE TITLE
Invalid character in Chunk ID (WAVE Module)

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#278]
We have this header for a BWAVE created in Pro Tools: 

      52 49 46 46 BA 5B 56 BF 57 41 56 45 4A 55 4E 4B 5C 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 62 65 78 74 5A 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 72 6F 20 54 6F 6F 6C 73 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 38 67 59 4E 21 76 39 37 68 6B 64 61 61 61 47 6B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 32 30 31 37 2D 30 39 2D 32 00 31 37 3A 32 35 3A 32 32 00 70 99 14 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 66 6D 74 20 28 00 00 00 01 00 02 00 00 77 01 00 00 CA 08 00 06 00 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 6D 69 6E 66 10 00 00 00 AC D3 7D CE 7F 36 D3 01 01 00 00 00 00 00 00 00 65 6C 6D 31 D6 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 64 61 74 61 3E

The resulting message for the whole file is 'Invalid character in Chunk ID' Character 0x00 and Offset 749. While the full file is 3GB, this header is within that range. Pulling it apart chunk-by-chunk then all the offsets seem to be accurate. The offset reported by JHOVE is between the 'fmt' chunk, and 'minf' chunk. 

So I guess we're just looking for a guide on what's throwing JHOVE's offsets off. 

Thanks,
Ross

**Comment by david-russo** [comment]
Hi Ross,

The WAVE module isn't dealing well with there being extra bytes in the Format chunk after the `cbSize` field indicates that there are no extra format bytes. Following a `cbSize` of `0`, there are 22 null bytes left in the chunk which JHOVE isn't skipping. This results in JHOVE trying to read the next chunk from within those null bytes.

The WAVE module should be ignoring everything after and including the `cbSize` field for PCMWAVEFORMAT files, so I'll mark it as a bug. There should also be a check put in place to make sure the entirety of a chunk has been read or skipped before looking for the next one.

**Comment by ross-spencer** [comment]
Great stuff. Thanks for the help.

**Comment by thorsted** [comment]
We have this issue in our workflow for some WAV files created with Protools. When I was looking into I found a couple things. One is the cbSize must equal 22. https://msdn.microsoft.com/en-us/library/windows/desktop/dd757714(v=vs.85).aspx
I ended up changing the byte at 0x2EA to 16 instead of 0, so the extra format bytes equal 22 and then JHOVE saw the extra padding correctly and ignored it.
