### ISSUE TITLE
examples file

### ISSUE THREAD

**Issue by brucefulton** [openpreserve/jhove#305]
I have a copy of the old jhove-examples.tar.gz file which seems to have gone missing from here, from the old source forge site, that is useful for teaching and instruction if someone wants to put it back on. Too big for an attachment here, about 30mb, and I don't have upload privs, so if someone attached to the project wants it, let me know how you would like to get it. Basically, copy it to the installation directory and untar it; it expands to an examples directory and subdirectories with several sample files of different types that can be tested.

**Comment by carlwilson** [comment]
Hi @brucefulton, I think these are still part of the git repository and they can be found here: https://github.com/openpreserve/jhove/tree/integration/jhove-core/src/main/examples. If you could confirm that these are the files you had in mind I can put a download up on an OPF server and publish the location, or from source might be fine.

**Comment by carlwilson** [comment]
Hi @brucefulton am closing this as the files are still in the project.
