### ISSUE TITLE
Missing documentation for WARC module

### ISSUE THREAD

**Issue by marhop** [openpreserve/jhove#307]
## Dev Effort
2D

## Description
Hello,

JHOVE (at least since version 1.16.1) ships with a module called "WARC-kb" that validates, well, WARC files. It's really nice and even extracts a lot of information from a WARC file.

However, it seems there exists no documentation whatsoever for this module, neither on <http://jhove.openpreservation.org/modules/> nor on GitHub. Am I missing something?

Thanks,
Martin

**Comment by samalloing** [comment]
I'll take this issue
