### ISSUE TITLE
XML validation ignores schema files configured in jhove.conf

### ISSUE THREAD

**Issue by marhop** [openpreserve/jhove#314]
## Dev Effort
2D

## Description
According to the [documentation of the XML module](http://jhove.openpreservation.org/modules/xml/) JHOVE can be configured to use local XML schema files when validating elements from a given XML namespace with a config file entry like this (example taken from the default config file):

    <module>
        <class>edu.harvard.hul.ois.jhove.module.XmlModule</class>
        <param>schema=http://www.example.com/schema;/home/schemas/exampleschema.xsd</param>
    </module>

However, JHOVE 1.18 seems to ignore these entries. Consider the following scenarios (assume the XML file is indeed valid):

1. XML file references a (local) schema file in a `schemaLocation` attribute; no config file entry → JHOVE uses the referenced file from the `schemaLocation` attribute, "well-formed and valid". This is correct.

2. XML file references a schema file in a `schemaLocation` attribute; config file contains entry that maps another local schema file to the same namespace → JHOVE uses the referenced file from the `schemaLocation` attribute, "well-formed and valid". This is arguable: I would prefer JHOVE to interpret the config file entry as overriding the `schemaLocation` attribute.

3. XML file references a *nonexistent* schema file in a `schemaLocation` attribute; config file contains entry that maps another, existing local schema file to the same namespace → JHOVE tries to use the referenced file from the `schemaLocation` attribute, "well-formed, but not valid" because the schema file is not found. This is arguable: I would prefer JHOVE to interpret the config file entry as overriding the `schemaLocation` attribute.

4. XML file does *not* reference a schema file; config file contains entry that maps an existing local schema file to the namespace → JHOVE does not use any schema file at all, "well-formed, but not valid". This is unnecessary: There is no conflict between two schema files (like in scenarios 2 and 3), so why does JHOVE not use the configured schema file?

Thanks for any clarification,
Martin

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [XML validation ignores schema files configured in jhove.conf #314 - Assigned to TBA](https://trello.com/c/KTPH5F4h/63-xml-validation-ignores-schema-files-configured-in-jhoveconf-314-assigned-to-tba)

**Comment by DinoAGW** [comment]
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [XML validation ignores schema files configured in jhove.conf #314 - Assigned to TBA](https://trello.com/c/KTPH5F4h/63-xml-validation-ignores-schema-files-configured-in-jhoveconf-314-assigned-to-tba)

nothing to see there, but Issue interesting for me as well

**Comment by pwinckles** [comment]
I implemented this here: https://github.com/UW-Madison-Library/jhove/compare/435f23381ff78357de3fbbc424952e1b7a3c31af..48d083b2394fc8b9426d9567744eff519284b830

**Comment by marhop** [comment]
Coming back to this issue six years later (JHOVE 1.28), I realize that ~I seem to have misunderstood the docs~ you have updated the docs (see #633): The configuration is not supposed to map from namespace URI to local schema file (as I thought), but from an external schema file path to a local schema file path!

So with a `schemaLocation="http://example.org/foo http://example.org/foo/schema.xsd"` entry in an XML instance the correct mapping is *not* this:

~~~xml
<!-- namespace URI → local schema file -->
<param>schema=http://example.org/foo;/etc/foo.xsd</param>
~~~

but this:

~~~xml
<!-- external schema file linked in schemaLocation → local schema file -->
<param>schema=http://example.org/foo/schema.xsd;/etc/foo.xsd</param>
~~~

And indeed, with the second variant JHOVE behaves as expected.
