### ISSUE TITLE
is sRGB_v4_ICC_preference.icc only used for tests?

### ISSUE THREAD

**Issue by jbreiden** [openpreserve/jhove#355]
Hi, I'm the Debian package maintainer for jhove. Is sRGB_v4_ICC_preference.icc only used for tests? Debian's automated system thinks the file it is not modifiable. If we don't need it for running jhove or jhove-gui, then I will remove it from Debian, to make life a little bit easier for us. Thanks!

> jhove source: lintian output: 'license-problem-md5sum-non-free-file jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/sRGB_v4_ICC_preference.icc usual name is sRGB_v4_ICC_preference.icc. Does not allow modification See also https://packages.debian.org/sid/icc-profiles.', automatically rejected package.

**Comment by jbreiden** [comment]
Until I hear otherwise, I will assume the answer is yes.

**Comment by carlwilson** [comment]
Hi @jbreiden . Sorry for the delay in answering, I can confirm that this is only a test resource and not part of the release package.
