### ISSUE TITLE
No jar-file when extracting "jhove-latest.jar.zip"

### ISSUE THREAD

**Issue by MerleFri** [openpreserve/jhove#356]
I wanted to install the newest version of jhove, but after extracting "jhove-latest.jar.zip" I only find folders, but no jar-file to install jhove on windows (10).

**Comment by carlwilson** [comment]
Hi @MerleFri, the file downloaded here: http://software.openpreservation.org/rel/jhove-latest.jar is a jar itself. Just run `java -jar jhove-latest.jar` and the installer will run.

**Comment by MerleFri** [comment]
Hi Carl, thanks for your help. It seems that my browser added a ".zip" to the jar, so Windows had problems identifying it. The java command helped, as well as deleting the ".zip" from the filename and double-click. Thank you!

**Comment by carlwilson** [comment]
No problem.
