### ISSUE TITLE
 Unexpected exception lava.lang.ClassCastException in PDF-hul 1.11 JOHVE 1.20.1

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#375]
## Dev Effort
2D

## Description
[F-03-B-823.pdf](https://github.com/openpreserve/jhove/files/2680299/F-03-B-823.pdf)

We have a large number of files all from the same collection that cause the same unexpected exception in JHOVE. I'm attaching one of them and happy to provide more if needed.

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unexpected exception lava.lang.ClassCastException in PDF-hul 1.11 JOHVE 1.20.1 #375 - Assigned to TBA](https://trello.com/c/KKmoAcRk/57-unexpected-exception-lavalangclasscastexception-in-pdf-hul-111-johve-1201-375-assigned-to-tba)
