### ISSUE TITLE
JHOVE 1.22 Invalid direct destination error message no longer includes referenced object

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#414]
In JHOVE 1.20 , the _Invalid direct destination_ error error message included the name of the referenced object, making it easier to trouble-shoot the PDF. This information is no longer present in JHOVE 1.22.0 RC (see attached screenshots for different output with same file). 
It would be helpful if the name could be reinstated as part of the error information output in some way.

![jhove_1-20-1_invalid-direct-destination](https://user-images.githubusercontent.com/13165865/54897370-6d8e9f80-4ec8-11e9-93e9-c16e7e5e9f48.png)
![jhove_1-22-0_invalid-direct-destination](https://user-images.githubusercontent.com/13165865/54897371-72ebea00-4ec8-11e9-9b18-23fdcf346935.png)

**Comment by carlwilson** [comment]
Hi @asciim0 can you please test the 1.24 RC and see whether this is still the case. I'll try to catch it in the RC still if not.
