### ISSUE TITLE
Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#416]
There are 108 occurrences of this problem. Why is this an issue?
Since: PMD 5.0

Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.

Example(s):
```java
public class HelloWorldBean {

  // Field declared before methods / inner classes - OK
  private String _thing;

  public String getMessage() {
    return "Hello World!";
  }

  // Field declared after methods / inner classes - avoid this
  private String _fieldInWrongLocation;
}
```
The full list of occurrences on codacy [is here](https://app.codacy.com/app/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiRXJyb3JQcm9uZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOls4OTZdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==)

**Comment by nvanderperren** [comment]
Hi, I'm working on this issue
