### ISSUE TITLE
Avoid unnecessary if..then..else statements when returning booleans

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#418]
There are 59 occurrences of this issue.
Why is this an issue?
Since: PMD 0.9

Avoid unnecessary if-then-else statements when returning a boolean. The result of the conditional test can be returned instead.

Example(s):

public boolean isBarEqualTo(int x) {

	if (bar == x) {		 // this bit of code...
		return true;
	} else {
		return false;
    }
}

public boolean isBarEqualTo(int x) {

   	return bar == x;	// can be replaced with this
}
Codacy's list of all occurrences can be [found here](https://app.codacy.com/app/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiRXJyb3JQcm9uZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOls4OTRdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==)

**Comment by nvanderperren** [comment]
On this now!

**Comment by carlwilson** [comment]
Thanks @nvanderperren
