### ISSUE TITLE
Document empty method body

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#421]
There are 22 occurrences of this issue.
Why is this an issue?
Since: PMD 3.4

Uncommented Empty Method Body finds instances where a method body does not contain statements, but there is no comment. By explicitly commenting empty method bodies it is easier to distinguish between intentional (commented) and unintentional empty methods.

Example(s):
```java
public void doSomething() {
}
```
A full list of occurrences can be found [here on Codacy](https://app.codacy.com/app/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiRXJyb3JQcm9uZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOls5NTNdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==)

**Comment by nvanderperren** [comment]
I will clean this one now! 🚿
