### ISSUE TITLE
Use one line for each declaration, it enhances code readability.

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#425]
There are 6 occurrences of this issue.
Why is this an issue?
Since: PMD 5.0

Java allows the use of several variables declaration of the same type on one line. However, it can lead to quite messy code. This rule looks for several declarations on the same line.

Example(s):
```java
String name;            // separate declarations
String lastname;

String name, lastname;  // combined declaration, a violation

String name,
       lastname;        // combined declaration on multiple lines, no violation by default.
                        // Set property strictMode to true to mark this as violation.
```
A full list of issues can be found [here on Codacy](https://app.codacy.com/app/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiRXJyb3JQcm9uZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOlsxMDM2XX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfV0=)

**Comment by garvita-jain** [comment]
Can I work on this issue?
Which code do I need to work on exactly?

**Comment by carlwilson** [comment]
Hi @garvita-jain the link I provided wasn't that helpful. Three are 7 occurrences of this problem [listed here](https://app.codacy.com/manual/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbMTAzNl19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltudWxsXX1d). In each case the declarations simply need to be split into individual  declarations, e.g.
```java
int i = 0, j = 0, k = 0;
```
becomes
```java
int i = 0;
int j = 0;
int k = 0;
```
Many thanks.
