### ISSUE TITLE
Please attach sources and javadoc to maven artifacts

### ISSUE THREAD

**Issue by ravn** [openpreserve/jhove#44]
When using JHove as a library it is nice if the sources are downloadable for an IDE to use (possibly also javadoc but that is not quite as important).

This must be explicitly configured in the pom.xml.  See https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html for instructions.

**Comment by carlwilson** [comment]
There are a few parts of the distributions that aren't finalised yet and this one seems a no brainer. Will add to the beta-milestone for mid-Sept and assign to me.

**Comment by carlwilson** [comment]
JavaDoc and Sources now deployed by Jenkins to [Artifactory](http://artifactory.opf-labs.org/artifactory/simple/opf-dev-local/org/openpreservation/jhove/jhove-core/1.12.20/) but I'm not the right person to sign off. Could you (@ravn) try 1.12.20 and see if it works for you?

**Comment by ravn** [comment]
It works for me.  Thank you :)
