### ISSUE TITLE
InfoMessage regarding version in catalog dictionary confuses locations

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#469]
The InfoMessage: "File header gives version as x.x, but catalog dictionary gives version as y.y" confuses the version attribution. 
For the attached example, the InfoMessage is "File header gives version as 1.7, but catalog dictionary gives version as 1.4", however, it is the other way around. File header shows 1.4, catalog dictionary shows 1.7. 

[content4.pdf](https://github.com/openpreserve/jhove/files/3539889/content4.pdf)

**Comment by carlwilson** [comment]
This has been fixed by @Anett16's contribution, please test using the 1.24 RC and close if confirmed.
