### ISSUE TITLE
Create translation resource packs for JHOVE error messages in different languages

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#474]
From JHOVE v1.22 it has been possible to add Java Resource packages that provide translations for JHOVE error messages. English messages already exist and are the default, a German translation is underway (see #467) but translations into any other languages are welcome. Obvious candidates include:

- [ ] French
- [ ] Dutch
- [ ] Spanish
- [ ] Danish
- [ ] Other

**Comment by ati95** [comment]
I'll participate : English to French

**Comment by Asbjoedt** [comment]
I can contribute Danish.

**Comment by carlwilson** [comment]
Hi @ati95 and @Asbjoedt many thanks for the offer of help and attending the call today. Let me know if you have any issues at all.

**Comment by ati95** [comment]
Hi @carlwilson Have you receive my requested to join the French language in the team JHOVE team, via Transifex ?
Where can we find the Google Docs "Contribution guide" ? I'm so sorry my listening comprehension is not enough for understand all in call

**Comment by Asbjoedt** [comment]
I have requested access to participate to Danish in Transifex but I cannot seem to open the translation. Can you help me?

**Comment by Asbjoedt** [comment]
@carlwilson thx I have access now. Can you confirm to me that the files open for translation are correct? It is only XML, WAVE and UTF-8 that have dedicated error messages. The other files consists of identical strings of HTML website code.

**Comment by Asbjoedt** [comment]
Hi @carlwilson. It would work best for me if you can find someone to review Danish translations.
