### ISSUE TITLE
Review JHOVE module documentation to ensure that it is accurate and up to date

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#475]
The [GitHub pages branch](https://github.com/openpreserve/jhove/tree/gh-pages/) is an orphan branch that contains all of the documentation, published at the [JHOVE website](https://jhove.openpreservation.org). Each module has a dedicated page, listed in the [modules directory](https://github.com/openpreserve/jhove/tree/gh-pages/modules). Each module's documentation needs to be reviewed to check that:

- [ ] All references to supporting specifications and documentation are correct.
- [ ] The latest version of the specification is supported by JHOVE, if not this should be noted on the module documentation page.

**Comment by tomassehabiaga** [comment]
i will take the issue 😃

**Comment by samalloing** [comment]
Hi @tomassehabiaga 

Which modules will you work on? I want to help if it is necessary

Sam

**Comment by david-russo** [comment]
I'm starting work on the WAVE-hul page.
