### ISSUE TITLE
jhove installer: more information in window of step 1

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#49]
The step 1 info ("Please read the following information:") currently only includes the jhove logo and version number. Would be beneficial to have some more info here (such as github link - or a pointer towards the option to save the installation process into an auto-install script at the end).

**Comment by carlwilson** [comment]
No time to do this on the Hack Day as coordinating and testing took priority, returning to the 1.16 fold.

**Comment by carlwilson** [comment]
The installer first page now includes:
- a link to the JHOVE website;
- a link to JHOVE on GitHub; and
- a link to the OPF website.

Am happy to enhance further if there's direct requests but will consider this closed.
