### ISSUE TITLE
translation of external modules

### ISSUE THREAD

**Issue by samalloing** [openpreserve/jhove#506]
Hi,

The external modules like PNG are not translated yet, see for PNG https://github.com/openpreserve/jhove/blob/integration/jhove-ext-modules/src/main/resources/ErrorMessages.properties . 

Also WARC (https://github.com/openpreserve/jhove/blob/integration/jhove-ext-modules/src/main/java/edu/harvard/hul/ois/jhove/module/warc/MessageConstants.java) and GZip (https://github.com/openpreserve/jhove/blob/integration/jhove-ext-modules/src/main/java/edu/harvard/hul/ois/jhove/module/gzip/MessageConstants.java) are not translated, but in these cases the error messages are still in the code. 

Sam

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [translation of external modules #506 - Assigned to TBA](https://trello.com/c/2lvSgz5h/42-translation-of-external-modules-506-assigned-to-tba)
