### ISSUE TITLE
GIF Error Message Graphic Control Extension

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#512]
The GIF module checks 3 extension blocks for correct size: graphics control extension, plain text extension and application extension.
Syntax for plain text extension and wrong application extension is:
"wrong <plain text | application> extension block size"
For graphics control extension it just says
"Wrong graphics control block size"
Should be fixed to "wrong graphics control extension block size"

**Comment by asciim0** [comment]
Adressed this in pull request  #513

**Comment by carlwilson** [comment]
Fixed in the new v1.24 RC by your own hand no less :) thanks @asciim0
