### ISSUE TITLE
Display Error Message UI in output

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#519]
Potentially a very dumb question - but how do I display the Error Message IDs in the output? I've tried various files with TIFF-hul and PDF-hul in both UI and shell, alas, no success. 
I'm using v1.22.1  ( 2019-04-17)
Cheers,
Micky

**Comment by asciim0** [comment]
Addition to this Issue: 
Error IDs should be added to UI output.  Attached are the view of the same execution on a TIFF file - one shows the view directly in the UI Rep Viewer, the other is the result of the UI export via "save as". Both should show the Error ID of the HUL. I tested this with the TIFF-hul.

<img width="519" alt="UI_save-as_result" src="https://user-images.githubusercontent.com/13165865/69516055-d7c47c00-0f50-11ea-8d0b-1a1e00718bd2.png">
<img width="479" alt="UI_View" src="https://user-images.githubusercontent.com/13165865/69516066-de52f380-0f50-11ea-88d9-bf1ec5f4181a.png">

**Comment by carlwilson** [comment]
I've added a sub-node that provides a message ID if that exists. Please test and confirm in the new v1.24 RC.
