### ISSUE TITLE
PDF-hul: Error ID not shown for "Invalid object definition" error

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#521]
The error output for PDF-hul error "Invalid object definition" error does not display the error ID in the output. The output simply is, e.g.:

###
  Size: 622
  Format: PDF
  Status: Not well-formed
  SignatureMatches:
   PDF-hul
  ErrorMessage: Invalid object definition
   Offset: 467
  MIMEtype: application/pdf
###

According to ErrorMessages.Properties, IDs  PDF-HUL-35, PDF-HUL-36, 
PDF-HUL-37 and PDF-HUL-38 should be assigned. 
I'm attaching a couple of files that display this behavior. More can be found in the iPRES PDF testcorpus (I can't seem to find it here, please let me know if you need more examples).

[T02-01_003_document-catalog-indirecte-pages-reference-missing.pdf](https://github.com/openpreserve/jhove/files/3885115/T02-01_003_document-catalog-indirecte-pages-reference-missing.pdf)
[T02-01_005_document-catalog-type-key-missing.pdf](https://github.com/openpreserve/jhove/files/3885116/T02-01_005_document-catalog-type-key-missing.pdf)

**Comment by carlwilson** [comment]
Fixed by v1.24 RC, please test and close if confirmed.
