### ISSUE TITLE
PDF-hul: Error ID not shown for "Invalid cross-reference table" error

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#525]
The error output for PDF-hul error "Invalid cross-reference table" error does not display the error ID in the output. The output simply is, e.g.:

(...)
  Size: 642
  Format: PDF
  Status: Not well-formed
  SignatureMatches:
   PDF-hul
  ErrorMessage: Invalid cross-reference table
   Offset: 464
  ID: PDF-HUL-85
  ErrorMessage: No document catalog dictionary
   Offset: 0
  MIMEtype: application/pdf
(...)

According to ErrorMessages.Properties, IDs PDF-HUL-68 or PDF-HUL-69 should be assigned.
I'm attaching a sample file for this behavior.

[T02-03_005_page-object-parent-contains-array.pdf](https://github.com/openpreserve/jhove/files/3885226/T02-03_005_page-object-parent-contains-array.pdf)

**Comment by carlwilson** [comment]
Fixed by v1.24 RC, please test and close if confirmed.
