### ISSUE TITLE
PDF-hul: Error ID not shown for "Improperly nested array delimiters" error

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#526]
The error output for PDF-hul error "Improperly nested array delimiters" error does not display the error ID in the output. The output simply is, e.g.:

(...)
 Size: 636
  Format: PDF
  Version: 1.4
  Status: Not well-formed
  SignatureMatches:
   PDF-hul
  ErrorMessage: Improperly nested array delimiters
   Offset: 122
  ErrorMessage: Improperly nested array delimiters
   Offset: 122
  MIMEtype: application/pdf
(...)

According to ErrorMessages.Properties, ID PDF-HUL-34 should be assigned.
I'm attaching a sample file for this behavior.

[T03_007_offset_wrong.pdf](https://github.com/openpreserve/jhove/files/3885235/T03_007_offset_wrong.pdf)

**Comment by carlwilson** [comment]
Fixed by v1.24 RC, please test and close if confirmed.
