### ISSUE TITLE
PDF-hul: Error ID not shown for "Illegal operator in cross-reference table" error

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#527]
The error output for PDF-hul error "Illegal operator in cross-reference table" error does not display the error ID in the output. The output simply is, e.g.:

(...)
  Size: 635
  Format: PDF
  Status: Not well-formed
  SignatureMatches:
   PDF-hul
  ErrorMessage: Illegal operator in cross-reference table
   Offset: 519
  MIMEtype: application/pdf
(...)

According to ErrorMessages.Properties, ID PDF-HUL-84 should be assigned.
I'm attaching a sample file for this behavior.

[T03_009_invalid-keyword-entry.pdf](https://github.com/openpreserve/jhove/files/3885239/T03_009_invalid-keyword-entry.pdf)

**Comment by carlwilson** [comment]
Fixed by v1.24 RC, please test and close if confirmed.
