### ISSUE TITLE
PDF-hul: Error ID not shown for "Root entry missing in trailer dictionary" error

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#528]
The error output for PDF-hul error "Root entry missing in trailer dictionary" error does not display the error ID in the output. The output simply is, e.g.:

(...)
  Size: 624
  Format: PDF
  Status: Not well-formed
  SignatureMatches:
   PDF-hul
  ErrorMessage: Root entry missing in trailer dictionary
   Offset: 603
  ID: PDF-HUL-85
  ErrorMessage: No document catalog dictionary
   Offset: 0
  MIMEtype: application/pdf
(...)

According to ErrorMessages.Properties, ID PDF-HUL-75 should be assigned.
I'm attaching a sample file for this behavior.

[T04_011_trailer-no-root-key-value-pair.pdf](https://github.com/openpreserve/jhove/files/3885256/T04_011_trailer-no-root-key-value-pair.pdf)

**Comment by carlwilson** [comment]
Fixed by v1.24 RC, please test and close if confirmed.
