### ISSUE TITLE
PDF-hul: Error ID not shown for "Malformed dictionary: Vector must contain an even number of objects, but has {0}" error"

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#529]
The error output for PDF-hul error "Malformed dictionary: Vector must contain an even number of objects, but has {0}" error does not display the error ID in the output. The output simply is, e.g.:

(...)
  Size: 634
  Format: PDF
  Status: Not well-formed
  SignatureMatches:
   PDF-hul
  ErrorMessage: Malformed dictionary: Vector must contain an even number of objects, but has 5
   Offset: 613
  MIMEtype: application/pdf
(...)

According to ErrorMessages.Properties, PDF-HUL-41 should be assigned.
I'm attaching a sample file for this behavior.

[T04_012_trailer-root-no-indirect-reference.pdf](https://github.com/openpreserve/jhove/files/3885258/T04_012_trailer-root-no-indirect-reference.pdf)

**Comment by carlwilson** [comment]
Fixed by v1.24 RC, please test and close if confirmed.
