### ISSUE TITLE
PDF-hul: Error ID possibly not shown for "Size entry missing in trailer dictionary" error

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#531]
In the attached sample file, the error output for PDF-hul error "Size entry missing in trailer dictionary" error does not display the error ID in the output. However, the file also contains a "Validation ended prematurely due to an unhandled exception." error - I am not sure if the error ID was simply not assigned due the thrown unhandled error. The output is: 

(...)
  Size: 628
  Format: PDF
  Status: Unknown
  SignatureMatches:
   PDF-hul
  ErrorMessage: Size entry missing in trailer dictionary
   Offset: 607
  ErrorMessage: Validation ended prematurely due to an unhandled exception.
  MIMEtype: application/pdf
(...)

The according file is attached.

[T04_015_trailer-no-size-key-value-pair.pdf](https://github.com/openpreserve/jhove/files/3885276/T04_015_trailer-no-size-key-value-pair.pdf)

**Comment by carlwilson** [comment]
The "Size entry missing.." error now has an ID `PDF-HUL-74`, the lack of an ID for the premature end is still an issue. Ideally that should be raised as a new issue and this closed if the 1.24 RC fixes the specific PDF error.

**Comment by carlwilson** [comment]
The issue needs triage to tease out the general issue covering the lack of error message for some of JHOVE's core error messages. If you're taking this issue on please contact @carlwilson for some tips to get started.

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PDF-hul: Error ID possibly not shown for "Size entry missing in trailer dictionary" error #531 - Assigned to Sam Alloing samalloing](https://trello.com/c/w9Md1pr7/38-pdf-hul-error-id-possibly-not-shown-for-size-entry-missing-in-trailer-dictionary-error-531-assigned-to-sam-alloing-samalloing)
