### ISSUE TITLE
PDF-hul: error message "edu.harvard.hul.ois.jhove.module.pdf.Keyword cannot be cast to edu.harvard.hul.ois.jhove.module.pdf.Numeric"

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#533]
The attached file reports the validation error "edu.harvard.hul.ois.jhove.module.pdf.Keyword cannot be cast to edu.harvard.hul.ois.jhove.module.pdf.Numeric".
It would help to assign such errors to a PDF-hul for easier classification. Also, the error message be clearer (i.e., what keyword cannot be cast).

[T03_003_number-of-entries-missing.pdf](https://github.com/openpreserve/jhove/files/3885304/T03_003_number-of-entries-missing.pdf)

**Comment by carlwilson** [comment]
The class cast error now has an ID, it signifies a problem with the XREF table so I've taken that ID and added the class cast message as a sub-message. It's difficult to add clarity with the code in it's current form as it's not possible to know what the class that's failed to be cast (in this case `edu.harvard.hul.ois.jhove.module.pdf.Keyword`) will be so I can't reliably call a method.

Please confirm that the 1.24 release candidate fixes this and close if happy, comment if not :)

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FEAT - List available translations #553 - Assigned to TBA](https://trello.com/c/IOSevocE/36-feat-list-available-translations-553-assigned-to-tba)
