### ISSUE TITLE
Menus get lost when closing document window in GUI on OS X

### ISSUE THREAD

**Issue by gmcgath** [openpreserve/jhove#55]
If I "Open" a file with the GUI version of JHOVE version 12 beta and then close it again, bringing the focus back to the main window, the File, Edit, and Help menus disappear. They can be restored by bringing up "About JHOVE" from the JhoveView menu and then closing the resulting window. This was on OS X 10.10.5 (Yosemite).

After noticing this in 1.12 beta, I tried it with 1.9 and got the same result. It seems I should have noticed if it was happening all along. I tried it on Linux, and the problem doesn't occur there. I suspect it's something that's turned up in recent versions of OS X.

**Comment by gmcgath** [comment]
Updating to Java 1.7.0_79-b15 made the problem go away. I think this can be closed, if no one else is seeing the problem.

**Comment by carlwilson** [comment]
Closing as this doesn't seem to be a problem, Java Swing can behave a little oddly at times.
