### ISSUE TITLE
Junit test errors in JSONHandlerTest

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#572]
Trying to build from source to prepare for the upcoming week I'm seeing the following failures in the JSON handler tests. It seems that the expected date is not being matched and therefore replaced with `DUMMY` date. 
```
Failed tests: 
  JsonHandlerTest.testShow:167 test expected:<...1","executionTime":"[DUMMY]"}}> but was:<...1","executionTime":"[2020-04-26T20:29:43-04:00]"}}>
  JsonHandlerTest.testShowApp:187 expected:<...1","executionTime":"[DUMMY]","app":{"api":{"ver...> but was:<...1","executionTime":"[2020-04-26T20:29:43-04:00]","app":{"api":{"ver...>
  JsonHandlerTest.testShowModule:230 expected:<...1","executionTime":"[DUMMY]","module":{"name":"...> but was:<...1","executionTime":"[2020-04-26T20:29:43-04:00]","module":{"name":"...>
  JsonHandlerTest.testShowOutputHandler:208 expected:<...1","executionTime":"[DUMMY]","handler":{"name":...> but was:<...1","executionTime":"[2020-04-26T20:29:43-04:00]","handler":{"name":...>
  JsonHandlerTest.testShowRepInfo:259 expected:<...1","executionTime":"[DUMMY]","repInfo":{"uri":"...> but was:<...1","executionTime":"[2020-04-26T20:29:43-04:00]","repInfo":{"uri":"...>
```
It looks like the date-time replacement string needs to include timezone differences, extending the regex to include plus/minus timezone differences (optionally) might do the trick:
```
-       private static final String TIME_PATTERN = "\"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\+[0-9]{2}:[0-9]{2})?\"";
+       private static final String TIME_PATTERN = "\"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\+[0-9]{2}:[0-9]{2})?((-|\\+)[0-9]{2}:[0-9]{2})?\"";
```

The addition is simply: `((-|\\+)[0-9]{2}:[0-9]{2})?`

We can tests on regex101: [here](https://regex101.com/r/f4J2X0/1)

E.g. `2020-04-26T20:29:43-04:00`

Running the tests with `mvn -Dtest=JsonHandlerTest test`

**Comment by carlwilson** [comment]
OK, @ross-spencer I'll use a Docker box to switch locale and give this a test. Am liking the regex idea and will take a look.

**Comment by carlwilson** [comment]
Hi @ross-spencer, I'm going to start with this once I've finished assigning tasks tomorrow presuming I can get persuade a Docker container to TZ change for me. While the regex fix should work, I might review the code to see if there's a better way to test.

**Comment by ross-spencer** [comment]
Thanks @carlwilson. I'm up and running with the potential fix using the updated regex, so I can get working my end later today. But might of course have an impact for others. Totally worth looking at it through another lens.

**Comment by carlwilson** [comment]
Hi, @ross-spencer I realise that I have no idea which TZ you're currently residing in. Been a busy one today but throwing myself into hack tasks this evening.

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Junit test errors in JSONHandlerTest #572 - Assigned to Carl](https://trello.com/c/6O7SvvrX/74-junit-test-errors-in-jsonhandlertest-572-assigned-to-carl)

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Embedded JavaDoc needs updating #483 - Assigned to TBA](https://trello.com/c/09TCCx0T/43-embedded-javadoc-needs-updating-483-assigned-to-tba)

**Comment by karenhanson** [comment]
FWIW: the fix to TIME_PATTERN proposed by Ross on this issue resolves my issue as well (New York timezone - dates were coming out like this: `2020-10-29T09:49:38-04:00`).
