### ISSUE TITLE
Replace repeated string literals with constants.

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#573]
There are more than 1400 occurrences of this issue.
Why is this an issue?
Checks for multiple occurrences of the same string literal within a single file.

Rationale: Code duplication makes maintenance more difficult, so it can be better to replace the multiple occurrences with a constant.

The Java part of this article: http://rc3.org/2006/10/11/use-contants-instead-of-string-literals/ gives a clear example of how to address these issues.

You can find all occurrences of this issue [here on Codacy](https://app.codacy.com/manual/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE3NjAiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==).

The purpose of the current exercise is to tidy up any repetition, sticking to Don't Repeat Yourself principles. For now, it's best to restrict ourselves to eliminating duplication in individual files, and not worry about repetition across files. There are two reasons for this:

- it's hard looking for repetition across files, and Codacy is good at locating it within them; and
- we can ignore issues of scope, that is whether a particular constant should be `public` or `private`, all constants are declared `private`.

These are all constants, so they need to be declared as such with a `final` keyword. Because they're constants there are no threading or instance issues, and it's safe to make them `static` also, so there's a single class constant rather than one for each class instance. This gives us `private static final String` as our standard declaration. Another convention is that class constants have all capital names with `_`s used to separate words, e.g. `MAX_INT` and that all static class constants should be declared at the top of the class.

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replace repeated string literals with constants. #573 - Assigned to deanforsmith](https://trello.com/c/QypaLciF/70-replace-repeated-string-literals-with-constants-573-assigned-to-deanforsmith)

**Comment by tomokos2** [comment]
Hi, may I help with this issue at all?

**Comment by carlwilson** [comment]
> Hi, may I help with this issue at all?

Hi @tomokos2, apologies but a couple of issues have had my attention elsewhere for a day or two. You can indeed, could you join a Slack channel? If not I'll arrange a section and let you know on GitHub.
