### ISSUE TITLE
Remove redundant imports

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#574]
There are more than 10 occurrences of this issue.
Why is this an issue?
Checks for redundant import statements. An import statement is considered redundant if:

- It is a duplicate of another import when a class is imported more than once.
- The class non-statically imported is from the java.lang package, e.g. importing java.lang.String.
- The class non-statically imported is from the same package as the current package.

You can find links to all occurrences of this error [here on Codacy](https://app.codacy.com/manual/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE3ODciXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==)

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove redundant imports #574 - Assigned to deanforsmith](https://trello.com/c/HnAUdrL7/71-remove-redundant-imports-574-assigned-to-deanforsmith)
