### ISSUE TITLE
Update JHOVE's Maven dependencies

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#576]

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update JHOVE's Maven dependencies #576 - Assigned to TBA](https://trello.com/c/8WpavSmu/73-update-jhoves-maven-dependencies-576-assigned-to-tba)

**Comment by carlwilson** [comment]
Done as part of the preparation for 1.28.
