### ISSUE TITLE
JPEG/Exif image incorrectly "Not well-formed"

### ISSUE THREAD

**Issue by tledoux** [openpreserve/jhove#60]
When a JPEG file begins with a APP1 and has a APP0 after, the file is declared "Not well-formed" with the following message : "JFIF APP0 marker not at beginning of file"

Even though the file is indeed not conformant with JPEG JFIF standard, it still conforms to the JPEG/Exif standard (also known as  JEITA CP-3451) which Jhove is supposed to handle as specify in http://jhove.openpreservation.org/modules/jpeg/

The following file shows this behaviour
[20150213_140637.zip](https://github.com/openpreserve/jhove/files/116159/20150213_140637.zip)

**Comment by asciim0** [comment]
+1

**Comment by tledoux** [comment]
+1

**Comment by friesey** [comment]
+1
