### ISSUE TITLE
ICCProfiles in JPEG are not extracted

### ISSUE THREAD

**Issue by tledoux** [openpreserve/jhove#61]
When a JPEG file embeds a ICCProfile in an APP2 data segment, this information doesn't appear in the associated mix information (NisoImageMetadata) : the information is supposed to be located in the IccProfile element.

 Such an ICCProfile can be validated by intending to construct an java.awt.color.ICC_Profile with the getInstance() method in java.

**Comment by carlwilson** [comment]
This issue is very similar to #62 and can be done as a single piece of work. Its weighting of 13 points includes completing #62 also. Don't vote for this issue if you've already voted for #62.

**Comment by tledoux** [comment]
+1 (obviously...)

**Comment by asciim0** [comment]
+1
