### ISSUE TITLE
PDF with a large amount of whitespace takes days to process 

### ISSUE THREAD

**Issue by karenhanson** [openpreserve/jhove#614]
We have a PDF that is not well formed. It has ~100MB of whitespace in the middle of it. The file gets stuck in a loop in `Tokenizer.getNext (long max)` - the loop is processing 1 whitespace at a time and adding it to _wsString. I can see the offset is incrementing, but it is running for several days and only processed 1/3 of the file. I note that while the token buffer is using a StringBuilder, the whitespace String is using `+=`. Not sure if this is causing the slowness. Unfortunately I can't share the example PDF. 

Note: I have a PR coming that will test the theory!

**Comment by karenhanson** [comment]
I have managed to create a PDF that can be used to replicate the issue by exporting a Word Doc to PDF with thousands of pages of spaces and then replacing a large chunk of its contents with "00" characters using a hex editor. This is a little heavy-handed and the resulting PDF is no longer valid, but it does demonstrate the long delay in processing even though this is a fraction of the size of the one I first saw the issue in. 
[lots-of-whitespace-test.pdf](https://github.com/openpreserve/jhove/files/4719438/lots-of-whitespace-test.pdf)

**Comment by MartinSpeller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PDF with a large amount of whitespace takes days to process #614 - Assigned Karen Hanson](https://trello.com/c/IGbn22g4/80-pdf-with-a-large-amount-of-whitespace-takes-days-to-process-614-assigned-karen-hanson)

**Comment by carlwilson** [comment]
Awesome :)
