### ISSUE TITLE
ICCProfiles in TIFF files are not extracted

### ISSUE THREAD

**Issue by tledoux** [openpreserve/jhove#62]
When a TIFF file embeds a ICCProfile in an TIFFTAG_ICCPROFILE (code 34675), this information doesn't appear in the associated mix information (NisoImageMetadata) : the information is supposed to be located in the IccProfile element.

Such an ICCProfile can be validated by intending to construct an java.awt.color.ICC_Profile with the getInstance() method in java.

**Comment by carlwilson** [comment]
This issue is very similar to #61 and can be done as a single piece of work. Its weighting of 13 points includes completing #61 also. Don't vote for this issue if you've already voted for #61.

**Comment by chhkb** [comment]
Christen, KBDB +1
