### ISSUE TITLE
Installer has expired!

### ISSUE THREAD

**Issue by pmay** [openpreserve/jhove#63]
Trying to run the latest installer gives the message:
"This installer has expired. Please download a new one from http://jhove.openpreserve.org"

Running on Win7, 64bit.

**Comment by pablogosse** [comment]
Ditto for me. I noticed this last week. Running on Scientific Linux 6, 64-bit. It fails with both the latest and DEV versions of the installer.

**Comment by pablogosse** [comment]
**UPDATE:** FYI I've been in contact with the good folks at OPF and they've indicated their technical lead is away this week but will be making this a priority when he returns next week.

**Comment by comstock** [comment]
...same for me. I'll subscribe to this issue hoping a notice will be posted when the new version is available. Thanks.

**Comment by comstock** [comment]
Can anyone speculate on when a new installer will be available?

![sshot_ 2016-03-21_28](https://cloud.githubusercontent.com/assets/5882987/13922575/4f7bf722-ef53-11e5-91b1-22197a096c0c.jpg)

**Comment by davidxcrowe** [comment]
Is this still an issue, because I'm getting the same error...

**Comment by gmcgath** [comment]
I've blogged about this. https://fileformats.wordpress.com/2016/04/06/jhovediw/
My impression is that OPF is focused now on VeraPDF, but could we please have a status report from them?

**Comment by pmay** [comment]
Is an expiry date on the installer even needed?

**Comment by carlwilson** [comment]
Apologies, the problem wasn't the code but the Jenkins build. Our server was somehow "altered" during the great Linode outage of January and I had limited time and success when trying to trace the issue previously.

**Comment by pablogosse** [comment]
Thanks so much Carl!

**Comment by shannonsdavis** [comment]
Attempting to use jhove in the command line on Mac gives the following error

Exception in thread "main" java.lang.NoClassDefFoundError: JHOVE
Caused by: java.lang.ClassNotFoundException: JHOVE
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
