### ISSUE TITLE
Maven build fails during Tests: parseInvalidWarcFileLonelyMonkeys

### ISSUE THREAD

**Issue by pmay** [openpreserve/jhove#64]
Failure in unit test assertions with expected not matching actual values.
Maven output attached
[builderror.txt](https://github.com/openpreserve/jhove/files/140832/builderror.txt)

**Comment by smmorrissey** [comment]
Sheila +1

**Comment by pmay** [comment]
+1

**Comment by asciim0** [comment]
+1

**Comment by friesey** [comment]
Yvonne Goportis +1

**Comment by carlwilson** [comment]
This was a windows build issue and I believe that it's fixed in version 1.16.
