### ISSUE TITLE
Switch language?

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#643]
Is there a way to switch the language for JHOVE (in particular the error codes) in preferences or elsewhere? I could neither find an option in the GUI, nor a flag in the cli.

**Comment by carlwilson** [comment]
Hi @asciim0 the change of language is automatic and is based on your machines localisation settings. If you let me know what OS your using I can let you know what you need to change to make this happen.

**Comment by david-russo** [comment]
For testing purposes, you can also set the locale of the JVM when it starts up. For JHOVE, you could do this by making a language-specific copy of `jhove.bat`, such as `jhove_de.bat`, and setting `user.country` and `user.language` options in the Java call at the bottom:

```
java -Duser.country=DE -Duser.language=de -Xss1024k -classpath "%CP%" Jhove -c "%CONFIG%" %*
```

Though we probably should have some way to allow users to configure their language independent of the operating system.

**Comment by asciim0** [comment]
If I understand correctly, the behavior here:
https://github.com/openpreserve/jhove/blob/47f077fcb09d3dd5720aeeb4abf27de5dac48d19/jhove-core/src/main/java/edu/harvard/hul/ois/jhove/messages/JhoveMessages.java#L90 
(or somewhere there about :-D ) 
takes the locale settings as the language parameter?
Would it be possible to replace this with a variable from e.g. jhove.conf? Is this on the roadmap already?
