### ISSUE TITLE
ErrorMessage: Unexpected Exception java.lang.ArrayIndexOutOfBoundsException in PDF-HUL

### ISSUE THREAD

**Issue by rolandsuri** [openpreserve/jhove#648]
A 2 MByte PDF 1.3 leads to this error when using JHOVE 1.24 and PDF-hul-94. The PDF File is fine according to the Adobe Preflight Profile for this PDF version. The error message looks like there is a problem with JHOVE or with the PDF-Hul and not with the file.

You may download the PDF from here:
https://doi.org/10.3929/ethz-b-000423059

ErrorMessage: 40
ID: NO-ID
ErrorMessage: Unexpected Exception java.lang.ArrayIndexOutOfBoundsException 
ID: PDF-HUL-94

**Comment by samalloing** [comment]
With the latest code (not released yet), this problem is resolved. The date is malformed, so it will show an error PDF-HUL-133

**Comment by carlwilson** [comment]
Tested and I concur, closing.
