### ISSUE TITLE
no gpg signature for latest stable jar on software.openpreservation.org

### ISSUE THREAD

**Issue by FelixSchwarz** [openpreserve/jhove#655]
Not sure if this is the right place but I noticed that the GPG signature download leads to a 404 error when trying to download the jhove jar from https://software.openpreservation.org/ . The link points to https://software.openpreservation.org/releases/jhove-latest.jar.asc

**Comment by carlwilson** [comment]
Thanks for the report @FelixSchwarz this is now fixed.
