### ISSUE TITLE
Installer expired warning directs to wrong web address

### ISSUE THREAD

**Issue by pmay** [openpreserve/jhove#68]
The warning that the installer has expired directs you to http://jhove.openpreserve.org.

This should be http://jhove.openpreservation.org.

![jhoveinstallererror](https://cloud.githubusercontent.com/assets/1150504/14387764/c7c38ec2-fda2-11e5-959c-07a1b4469a88.jpg)

**Comment by asciim0** [comment]
+1

**Comment by carlwilson** [comment]
No time to do this on the Hack Day as coordinating and testing took priority, returning to the 1.16 fold.

**Comment by pmay** [comment]
Why does the installer even have an expiry date?

**Comment by carlwilson** [comment]
It no longer does, it was originally intended to stop the beta version getting used as a release. It survived because I forgot about it, then it expired (bad) and caused issues. I'm sure that purging the expiration from the installer fixes this also.
