### ISSUE TITLE
XMLHandler's expression of PropertyArity.MAP does not validate with JHOVE 1.8 XSD 

### ISSUE THREAD

**Issue by karenhanson** [openpreserve/jhove#686]
Some modules (e.g. WARC, GZIP) use PropertyArity.MAP in their report. When the XMLHandler outputs the report, records are expressed as follows:
```
<property>
     <name>Record</name>
     <values arity="Map" type="String">
      <value key="Record offset in WARC file.">0</value>
      <value key="Warc-Date header value.">2021-07-08T16:29:49Z</value>
      <value key="Warc-Record-ID header value.">&lt;urn:uuid:404a9418-4bff-4efb-a3ac-88f975aba3d6&gt;</value>
      <value key="Record-ID-Scheme value.">urn</value>
      <value key="Content-Type header value.">application/warc-fields</value>
      <value key="Content-Length header value.">168</value>
      <value key="Warc-Type header value.">warcinfo</value>
      <value key="hasPayload value.">true</value>
      <value key="PayloadLength value.">168</value>
      <value key="isNonCompliant value.">false</value>
      <value key="WarcFilename header value.">example_0.warc.gz</value>
     </values>
</property>
```
This is generated from this code in XMLHandler:
https://github.com/openpreserve/jhove/blob/47f077fcb09d3dd5720aeeb4abf27de5dac48d19/jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java#L816-L857

When the output is validated against JHOVE 1.8 XSD, however, it outputs the message: "<value> does not have a key attribute"
Here is the section of the 1.8 XSD that validates the value field. There is no key attribute specified:
```
<xs:element name="value">
    <xs:annotation>
        <xs:documentation>The value element can contain a scalar actual value or additional markup from known namespaces</xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
        <xs:sequence>
            <xs:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
```

It seems that the XMLHandler should output the XML in a different format that is compatible with the JHOVE 1.8 schema.

**Comment by karenhanson** [comment]
@carlwilson do you have any thoughts on the appropriate way to fix this? Possible options: 
- update the JHOVE schema to allow `key` on `value` (not sure of the process to update schema)
- modify the GZIP and WARC module to output Lists instead (though if there is a MAP option it should be possible to use it)
- Change XMLHandler to represent a Map in a form that is supported by the schema (maybe use the same arrangement as a List or Array). I think that would be something like this (which is very verbose compared to current MAP):
```
<properties>
  <property>
   <name>Records</name>
   <values arity="List" type="Property">
   <property>
    <name>Record</name>
    <values arity="Map" type="Property">
    <property>
     <name>Record offset in WARC file.</name>
     <values arity="Scalar" type="Integer">
      <value>0</value>
     </values>
    </property>
    <property>
     <name>Warc-Date header value.</name>
     <values arity="Scalar" type="Date">
      <value>2022-02-22T18:00:57Z</value>
     </values>
    </property>
```
    
Is there another option? I might submit a PR for this if I can figure it out, but not sure who manages the schema if that's the preferred solution.

**Comment by karenhanson** [comment]
Noting that XMLHandler has included the `PropertyArity.Map` code as long as the GitHub code repo goes back. Since it is used in the GZIP and WARC modules, that means there is XML in archives with the `key` attribute already in there. Talked to my systems colleagues about this and all agreed changing the XSD to allow `<value key=` would be most efficient for backward compatibility, level of effort, and keeping the report compact. Not sure how difficult that is, or how schema changes are decided - does that sound right? Happy to contribute any way I can.

**Comment by carlwilson** [comment]
Hi @karenhanson sorry, I missed this initially. I've made a start on what's going to be at least 2 weeks getting the next release together. I will take a look at this early next week and get back with some thoughts for your Tuesday (22/11).

**Comment by carlwilson** [comment]
Hi @karenhanson , agree that the schema change is the way forward here, and we need to be backward compatible. I handle the changing and hosting of the schema, but am happy to take a contribution with the appropriate change and I'll take it from there.

**Comment by karenhanson** [comment]
I think changing the value element to this should do it. I'll email you a copy of the file with the proper tabbed indents.
```
<xs:element name="value">
    <xs:annotation>
        <xs:documentation>The value element can contain a scalar actual value or additional markup from known namespaces</xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
        <xs:sequence>
            <xs:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>Attribute contains the key name for key-value pairs in a Map property</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:element>
```

**Comment by carlwilson** [comment]
Hi @karenhanson apologies, I've been ill for a bit of a protracted spell as the year started. A 1.28 RC is out today and this should be in place as the schema now. Will close on confirmation.

**Comment by karenhanson** [comment]
Confirmed - the new version looks good. Thank you so much!

**Comment by karenhanson** [comment]
@carlwilson was just doing some end-to-end testing on this. The uploaded schema looks good, but just noted that the XML Handler is still referencing 1.8 instead of 1.9:
https://github.com/openpreserve/jhove/blob/94da570caa55759354fa6fcd50e4ea7edbba1e7d/jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java#L104
Save as XML produces the following header (note "/1.8/jhove.xsd"):
```
<?xml version="1.0" encoding="UTF-8"?>
<jhove xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.openpreservation.org/ois/xml/ns/jhove" xsi:schemaLocation="http://schema.openpreservation.org/ois/xml/ns/jhove https://schema.openpreservation.org/ois/xml/xsd/jhove/1.8/jhove.xsd" name="JhoveView" release="1.28.0-RC1" date="2023-03-16">
```
Not sure if you planned to change it separately, so thought I should log this.

**Comment by carlwilson** [comment]
Thanks @karenhanson , I didn't mean to fix it separately, just an oversight that will be fixed in an RC patch next week.

**Comment by carlwilson** [comment]
I believe that this is fixed now and this can be closed?

**Comment by karenhanson** [comment]
Yes this can be closed
