### ISSUE TITLE
Java exception Mac

### ISSUE THREAD

**Issue by shannonsdavis** [openpreserve/jhove#69]
Running jhove in command line on Mac gives the following error:

Exception in thread "main" java.lang.NoClassDefFoundError: JHOVE
Caused by: java.lang.ClassNotFoundException: JHOVE
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by carlwilson** [comment]
Hi,

that error often occurs when JHOVE can't see the config file, but I can't replicate it on a Mac mini. I could do with a little more information:
- the command you're using to run JHOVE with the option switches
- a directory listing of the JHOVE installation you're using

Thanks.

**Comment by shannonsdavis** [comment]
That error it turned out was due to terminal using an outdated version of java, which I've updated. I am still getting an error however when running "java jhove mhs_A1643_B61f13i0001_1.tif" The new error is "Error: Could not find or load main class jhove"

216:jhove-beta ssdavis$ ls -lR | more
total 16
drwxr-xr-x  4 ssdavis  staff   136 Apr 12 16:07 Uninstaller
drwxr-xr-x  3 ssdavis  staff   102 Apr 12 16:07 bin
drwxr-xr-x  3 ssdavis  staff   102 May  5 10:09 conf
-rwxr-xr-x  1 ssdavis  staff  2367 May  5 10:09 jhove
-rwxr-xr-x  1 ssdavis  staff  2371 May  5 10:09 jhove-gui

./Uninstaller:
total 2464
-rw-r--r--  1 ssdavis  staff      267 May  5 10:09 install.log
-rw-r--r--  1 ssdavis  staff  1254953 May  5 10:09 uninstaller.jar

./bin:
total 2472
-rwxr-xr-x  1 ssdavis  staff  1264267 Apr 12 10:20 jhove-apps-1.12.42.jar

./conf:
total 8
-rw-r--r--  1 ssdavis  staff  1633 May  5 10:09 jhove.conf

**Comment by carlwilson** [comment]
Sorry Shannon, I missed this. I think the issue is that you're using invoking the Java JVM on a shell script, From the jhove directory try `./jhove <somefile>` instead of `java jhove <somefile>`. This should help:

```
$ pwd
~/jhove/1.12

$ ls -al
total 24
drwxr-xr-x  8 cfw  staff   272 11 May 11:14 .
drwxr-xr-x  4 cfw  staff   136 12 May 14:21 ..
-rw-r--r--  1 cfw  staff  3415 11 May 11:14 .installationinformation
drwxr-xr-x  4 cfw  staff   136 11 May 11:14 Uninstaller
drwxr-xr-x  3 cfw  staff   102 11 May 11:14 bin
drwxr-xr-x  3 cfw  staff   102 11 May 11:14 conf
-rwxr-xr-x  1 cfw  staff  2363 11 May 11:14 jhove
-rwxr-xr-x  1 cfw  staff  2367 11 May 11:14 jhove-gui

$ java jhove
Error: Could not find or load main class jhove

$ ./jhove -v
Jhove (Rel. 1.12.47, 2016-05-10)
 Date: 2016-05-26 20:53:04 BST
 App:
  API: 1.12.47, 2016-05-10
  Configuration: /Users/cfw/jhove/1.12/conf/jhove.conf
  JhoveHome: /Users/cfw/jhove/1.12
  Encoding: utf-8
  TempDirectory: /var/folders/0p/3lqbr8vn5ng7d6545nv8v5s80000gn/T/
  BufferSize: 131072
  Module: AIFF-hul 1.3
  Module: ASCII-hul 1.3
  Module: BYTESTREAM 1.3
  Module: GIF-hul 1.3
  Module: GZIP-kb 0.1
  Module: HTML-hul 1.3
  Module: JPEG-hul 1.2
  Module: JPEG2000-hul 1.3
  Module: PDF-hul 1.7
  Module: TIFF-hul 1.7
  Module: UTF8-hul 1.6
  Module: WARC-kb 1.0
  Module: WAVE-hul 1.3
  Module: XML-hul 1.4
  OutputHandler: Audit 1.1
  OutputHandler: TEXT 1.5
  OutputHandler: XML 1.7
  Usage: java JHOVE [-c config] [-m module] [-h handler] [-e encoding] [-H handler] [-o output] [-x saxclass] [-t tempdir] [-b bufsize] [-l loglevel] [[-krs] dir-file-or-uri [...]]
  Rights: Derived from software Copyright 2004-2011 by the President and Fellows of Harvard College. Version 1.7 to 1.11 independently released. Version 1.12 onwards released by Open Preservation Foundation. Released under the GNU Lesser General Public License.
```

**Comment by shannonsdavis** [comment]
I downloaded the newest version of jhove and didn't run into any errors this time. Thanks for your help!

**Comment by carlwilson** [comment]
No problem.
