### ISSUE TITLE
JHOVE inappropriately defaults the TIFF Exif Version tag to `0220`

### ISSUE THREAD

**Issue by pwinckles** [openpreserve/jhove#690]
JHOVE defaults `ExifVersion` to `0220` [here](https://github.com/openpreserve/jhove/blob/integration/jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/ExifIFD.java#L281). I assume that it does this because of [this document](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/exifversion.html). However, that document is just describing the value that should be used when writing that field, assuming the then most recent version of the Exif spec. For comparison, [version 2.3 of the spec](https://web.archive.org/web/20190624045241if_/http://www.cipa.jp:80/std/documents/e/DC-008-Translation-2019-E.pdf) states that the field should be defaulted to `0232`. As such, it is inappropriate to default this field when _reading_.

**Comment by carlwilson** [comment]
A quick read here and I'm inclined to agree. This sentence seems fairly authoritative 

> Nonexistence of this field is taken to mean nonconformance to the Exif standard.

This raises the possibility of nonexistence and marks it as a validation issue, there's no mention of taking a default value. Merging #691 for the imminent 1.26 release candidate, thanks for the work.
