### ISSUE TITLE
JHOVE builds have stopped due to TravisCI.org has been sunset 

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#692]
TravisCI.org has been sunset and builds have ceased as of June 15. 

![image](https://user-images.githubusercontent.com/1880412/128476709-4512ff4e-5e81-4834-ad5f-6cf112db2653.png)

We're seeing CI left incomplete in this repo: 

![image](https://user-images.githubusercontent.com/1880412/128476756-f2ccfabd-d17a-4bcc-bbe6-1b7a59caec86.png)

I'm sure folks are largely aware, but perhaps there's an opportunity with this ticket to discuss alternatives and seek support in migrating? 

Tangentially connected to: https://github.com/openpreserve/jhove/issues/146

**Comment by carlwilson** [comment]
The CI builds for JHOVE are now GitHub actions based so closing this.
