### ISSUE TITLE
Wiki: Can't access example file for JPEG-HUL-9

### ISSUE THREAD

**Issue by marhop** [openpreserve/jhove#697]
Hi,

The Wiki page https://github.com/openpreserve/jhove/wiki/JPEG-hul-Messages#jpeg-hul-9 links to an [example file on Google Drive](https://drive.google.com/open?id=0Bxn2YxzZ-3xCVlFpNldDb2FPRFk) which I can't access (no permissions) even after Google login.

Cheers,
Martin

**Comment by thorsted** [comment]
I believe that is my sample.
![MissingJFIF](https://user-images.githubusercontent.com/213296/146036854-b95c6912-ac1a-4434-97f5-6e41024b72fe.jpg)
https://drive.google.com/file/d/0Bxn2YxzZ-3xCVlFpNldDb2FPRFk/view?usp=sharing&resourcekey=0-fomhzGi6oA4rNHzr2ZxISQ

**Comment by marhop** [comment]
Your new link works for me, thanks! Let's keep this issue open though until the wiki has been fixed, OK?

**Comment by marhop** [comment]
I fixed the link.
