### ISSUE TITLE
Wiki: Additional info for JPEG-HUL-9

### ISSUE THREAD

**Issue by marhop** [openpreserve/jhove#698]
Hi,

Apparently the Wiki cannot be edited?! I'd like to suggest the following info be added to the [JPEG-HUL-9 "File does not begin with SPIFF, Exif or JFIF segment" entry](https://github.com/openpreserve/jhove/wiki/JPEG-hul-Messages#jpeg-hul-9). Feel free to add further improvements!

Cheers,
Martin

---

## Impact

When this error is raised for a *well-formed but not valid* file it typically hints at an uncommon but not necessarily broken file structure. From the [JHOVE documentation](https://jhove.openpreservation.org/modules/jpeg/):

> A file which consists of a JPEG data stream, but does not contain the required segments for a JFIF, SPIFF, Exif, JTIP, or JPEG-LS file is considered well-formed but not valid.

In particular, the most common JPEG file formats JFIF and Exif expect a file to start with the hex sequence `ffd8 ffe0` (SOI + APP0) or `ffd8 ffe1` (SOI + APP1), respectively. However, the original JPEG specification ([ITU-T Rec. T.81](https://www.w3.org/Graphics/JPEG/itu-t81.pdf), Annex B) allows other data immediately after the SOI marker (e.g., a DQT marker) as well. That may not be in line with one of the abovementioned formats though which restrict the file structure in one way or another, leading to this error.

So as long as a file with this error opens correctly in a viewer (better yet, in several different viewers) and has no other errors it may just be an uncommon JPEG variant, making the final verdict a file format policy question.

## Remediation

As long as this is the only error in a file one of the following measures may be appropriate:

* Ignoring the error i.e., accepting the file format although it is (very) uncommon.
* Converting it to another, more common JPEG format like JFIF. (TODO With which tool?)
* Adding an APP0 segment like `ffe0 0010 4a46494600 0102 00 0001 0001 00 00` (must be adapted to the concrete file!) after the SOI marker to turn the file into a [JFIF](http://fileformats.archiveteam.org/wiki/JFIF) file. However, this is adventurous at best; don't try this at home!

**Comment by asciim0** [comment]
seems like i can edit it. just added your info to JPEG-HUL 9. Can you confirm you can see it?

thanks for sharing!

**Comment by marhop** [comment]
Looks good to me, thank you!

I wonder though - am I just too dumb to edit the Wiki myself or is this intentional? (Not that I expect you to know, but maybe @carlwilson?)
