### ISSUE TITLE
WaveModule->FormatChuk: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by RogerMathisen** [openpreserve/jhove#70]
Class: package edu.harvard.hul.ois.jhove.module.wave.FormatChunk

The setting of "compName" in readChunk() will give an ArrayIndexOutOfBoundsException for all "compressionCode" values greater than than the length of WaveStrings.COMPRESSION_INDEX[](eg. 0xfffe). 

Also the calculated value will be wrong for all values of "compressionCode" that is greater than 0xB.

**Comment by smmorrissey** [comment]
Sheila +1

**Comment by pmay** [comment]
+1

**Comment by asciim0** [comment]
+1
