### ISSUE TITLE
edu.harvard.hul.ois.jhove.ModuleBase: skipBytes() might not skip all requested bytes

### ISSUE THREAD

**Issue by RogerMathisen** [openpreserve/jhove#71]
For large Wavefiles (>100MB) it happens that not all bytes in the DataChunk are skipped as expected in the method:

public long skipBytes(DataInputStream stream, long bytesToSkip, ModuleBase counted)

this seems to be because the call:

long n = stream.skip(bytesToSkip);

Actually might skip fewer bytes than requested (This is also stated in the Java Documentation). If this occurs it will most probably cause the parsing of the Wave file to fail, since the pointer to the next chunk will be placed inside the DATA chunk.

To avoid this problem the "long n = stream.skip(bytesToSkip);" call could be placed inside a loop that continues until all the desired bytes are skipped, or no more bytes kan be skipped (ie n=0).

**Comment by smmorrissey** [comment]
Sheila +1

**Comment by pmay** [comment]
+1

**Comment by asciim0** [comment]
+1

**Comment by friesey** [comment]
+1
