### ISSUE TITLE
JHOVE 1.26-RC GUI is missing some modules

### ISSUE THREAD

**Issue by karenhanson** [openpreserve/jhove#735]
Installed JHOVE 1.26-RC from this blog link on Windows:
https://openpreservation.org/news/first-jhove-1-26-release-candidate-out-now/
Double-clicked jhove-gui.bat. The following message appears:
![image](https://user-images.githubusercontent.com/4070836/163466505-15102939-401a-4eb4-9e20-d753c45b58ee.png)
The **ASCII** module is missing. **EPUB**, **BYTESTREAM**, and **UTF-8** are also missing though it does not show an error for these.

**Comment by carlwilson** [comment]
Sorry travelling today. I'm 99% sure it's badly packaged by Jenkins is all. Unless I'm wrong fixed before Easter is out.

**Comment by karenhanson** [comment]
Tested RC2 and this is fixed.
