### ISSUE TITLE
How to switch languageCode to English?

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#742]
1.26 RC contains the feat to switch the language code using the config file. 
My system's default setting is German. I've managed to successfully switch the jhove output to French using 
<languageCode>fr</languageCode>
in jhove.config
However, I can't figure out how to switch it to English (which is what i wanted to do from the start). I've tried en, english, ENGLISH, en-US, default as input values.
What's the correct parameter to enter?

**Comment by carlwilson** [comment]
Hi, @asciim0 I've tested and reproduced this. In theory, the [Java function](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String-) takes [ITEF BCP 47 language tags](https://en.wikipedia.org/wiki/IETF_language_tag) and `en` is definitely valid. If I set my Linux session locale to `de_DE.UTF8` I can also use `fr` to get french messages but `en` yields german error messages. I suspect that the answer is in the mapping done when loading the internationalisation resources [here for the PDF module](https://github.com/openpreserve/jhove/tree/integration/jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf). Note that the English defaults are simply called: `ErrorMessages.properties` and that no `ErrorMessages_en.properties` exists. I think that I'll need a copy (or better still a symlink) that creates that file. I'll try to add a fix quickly as it simply adds a resource file and doesn't involve code changes.

**Comment by carlwilson** [comment]
I've now tested a fix based on the above idea and it works. I'll wait another day or two to see if there are any other issues to fix but will get a third RC out this week with this fix in at least.

**Comment by carlwilson** [comment]
fixed in v1.26
