### ISSUE TITLE
PDFa identification regression

### ISSUE THREAD

**Issue by pwinckles** [openpreserve/jhove#753]
I was just working on updating FITS to use the 1.26.0 jhove release, and discovered a regression in jhove's PDFa identification.

Take [this file](https://github.com/harvard-lts/fits/blob/main/testfiles/PDFa_equations.pdf) as an example.

In jhove 1.24 it reports the following:

```
Profile: Linearized PDF, Tagged PDF, ISO PDF/A-1, Level B 
```

And in jhove 1.26 it reports:

```
Profile: Linearized PDF, Tagged PDF
```

**Comment by david-russo** [comment]
Hi Peter,

Disabling PDF/A profile reporting was intentional (see issue #101 and PR #393) as the existing PDF/A identification and validation code in JHOVE was found to be unfit for purpose.

**Comment by pwinckles** [comment]
Ah, thank you. I had missed that.
