### ISSUE TITLE
JHOVE web pages should show which formats are supported

### ISSUE THREAD

**Issue by RvanVeenendaal** [openpreserve/jhove#754]
The OPF website links to the JHOVE product page https://openpreservation.org/tools/jhove/. The JHOVE product page links to the JHOVE resource page http://jhove.openpreservation.org/. The JHOVE resource page links to the Getting started page http://jhove.openpreservation.org/getting-started/. None of these pages include a full list of file formats you can currently validate using JHOVE. Perhaps you can only discover the full list after you downloaded and installed JHOVE?

Potential or new users of JHOVE, will find it useful to know what this tool can and can't do for them. I'd therefore like to propose including a list of currently (add a date/version number) supported file types/formats on JHOVE web pages. 

Perhaps this can be added to the grey area on https://openpreservation.org/tools/jhove/, similar to how the veraPDF page includes the fact that is is for validating PDF/A files.

**Comment by carlwilson** [comment]
Fixed by #776 thanks @GeorgiaMoppett
