### ISSUE TITLE
Incorrect settings in pom for 1.26 release

### ISSUE THREAD

**Issue by tledoux** [openpreserve/jhove#757]
The 1.26 release contains 2 incorrect settings with unexpected results.

In the pom.xml of the jpeg-hul module, the dependency with the tiff-hul module is set to 1.9.1 instead of 1.9.3 
which results in importing the 1.24 version in the maven repository.

Additionnaly, the parent pom.xml defines the compilation target of java 8 by the way of 
```
<java.source.version>1.8</java.source.version>
<java.target.version>1.8</java.target.version>
```
this leads to the bad call of the ByteBuffer.position(I) from ByteBuffer instead of Buffer when executing with a java 8 VM.
This is best explained in https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

The above properties should be changed by : `<maven.compiler.release>8</maven.compiler.release>`
in order to invoke the `--release` option during the compilation phase.

**Comment by carlwilson** [comment]
Thanks for this @tledoux, it looks like a patch is required, will look at this very soon.
