### ISSUE TITLE
New GPS tag

### ISSUE THREAD

**Issue by thorsted** [openpreserve/jhove#787]
Processing a file from the new iPhone 13/14 and iPad Pro, I get an "Unknown GPSInfo IFD tag"  error TIFF-HUL-17

The new tag is 31 - GPS Horizontal Positioning Error

There are other InfoMessages which are unknown, but the GPS tag is the only Error.

<pre> ReportingModule: TIFF-hul, Rel. 1.9.3 (2022-04-22)
  LastModified: 2022-08-23 15:32:21 MDT
  Size: 36597122
  Format: TIFF
  Version: 6.0
  Status: Well-Formed and valid
  SignatureMatches:
   TIFF-hul
  ErrorMessage: Unknown GPSInfo IFD tag: Tag = 31;
   ID: TIFF-HUL-17
   Offset: 18810
  MIMEtype: image/tiff</pre>

**Comment by carlwilson** [comment]
Thanks for logging this @thorsted it looks like a straightforward fix.
