### ISSUE TITLE
Small installation error message

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#845]
Looks like this has been part of the installer on Windows since at least 1.26, with the 1.28-rc today, seeing:

```text
C:\temp\tmp>java -jar jhove-installer-rc.jar
Command line arguments:
Cannot find named resource: 'packsLang.xml' AND 'packsLang.xml_eng'
```

I don't see any other immediate impact as everything loads fine just afterwards. 

```text
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19042 Build 19042
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Locale	United States
Time Zone	W. Europe Standard Time
```

**Comment by carlwilson** [comment]
Hi @ross-spencer it's an internationalisation artefact/warning from the installer but I will take a look at suppressing the message/changing a setting for the next release. The only thing that might change there is that I'm currently reviewing JHOVE's installer and we may switch altogether.
