### ISSUE TITLE
jHove doesn't report on a couple of TIFF tags:

### ISSUE THREAD

**Issue by perdrix52** [openpreserve/jhove#848]
Specifically:
TIFFTAG_STRIPOFFSETS and TIFFTAGSTRIPBYTECOUNTS

AsTiffTagViewer does report them correctly ...

StripOffsets (3 Long): 514, 16771762, 33543010
StripByteCounts (3 Long): 16771248, 16771248, 2496960

Here's a dropbox link to a file that contains those tags.

https://www.dropbox.com/s/moe5rtp4wg1ra21/MasterOffset_ISO200%20-%20good.tif?dl=0

Thanks, David

**Comment by carlwilson** [comment]
Hi @perdrix52 this won't be part of the finalised 1.28 release but we will take a look at this when we're planning the 1.30 release over the summer.

**Comment by perdrix52** [comment]
Thanks, David

**Comment by tledoux** [comment]
In fact, all these tags were correctly extracted and checked.
However, they were all stored in the NisoMetadata part of the information (see https://www.loc.gov/standards/mix/).
This information is displayed differently depending on the version of mix 0.2, 1.0, 2.0

Only the 0.2 version displayed this information.
This version is quite outdated and the default is to display the 2.0 version.

So the correction is to add those properties to the normal ones of the images.
There will be a duplication of the information is the case of 0.2 version.
