### ISSUE TITLE
Update utf8-hul/pom.xml when bumping version number of pdf-hul

### ISSUE THREAD

**Issue by EOltmanns** [openpreserve/jhove#855]
utf8-hul has a test dependency on pdf-hul which is currently not in
sync. This patch applies to v1.28.0:

```
diff --git a/jhove-modules/utf8-hul/pom.xml b/jhove-modules/utf8-hul/pom.xml
index 908c232c..fe92fff1 100644
--- a/jhove-modules/utf8-hul/pom.xml
+++ b/jhove-modules/utf8-hul/pom.xml
@@ -19,7 +19,7 @@
       <dependency>
         <groupId>org.openpreservation.jhove.modules</groupId>
         <artifactId>pdf-hul</artifactId>
-        <version>1.12.1</version>
+        <version>1.12.4</version>
         <scope>test</scope>
       </dependency>
   </dependencies>
```

**Comment by carlwilson** [comment]
Hmmm, so Maven usually does this automagically when using the versions plugin to bump versions. The only thing that has to be done by hand is the update to the installer manifests, that wouldn't affect this. This is looking like a re-issue job, not sure what's gone wrong there. I'm currently OOO with work but will look at this on my return.

**Comment by carlwilson** [comment]
hi @EOltmanns it turns out that this is a redundant Maven entry. I've removed the dependency and re-compiled and all is fine. I'll make that official in the code base shortly but this can safely be closed.
