### ISSUE TITLE
Feature request: Please continue signing tags

### ISSUE THREAD

**Issue by EOltmanns** [openpreserve/jhove#856]
v1.28.0 is not signed. On the whole, tags used to be signed in the
past and it would be great if that could be continued, so
(semi-)automated package builds will not fail on signature
verification.

**Comment by carlwilson** [comment]
Apologies @EOltmanns, this seems to be a bit of a breakdown in the automated packaging of JHOVE. I'll look at what's gone wrong and see if we can't remove that tag and replace it with a signed version.
