### ISSUE TITLE
publish 1.28.0 to central

### ISSUE THREAD

**Issue by pwinckles** [openpreserve/jhove#864]
It looks like the latest release, 1.28.0, is still not in central. Are you planning on publishing it there, or are you just using the OPF repository now?

**Comment by carlwilson** [comment]
Thanks for the catch @pwinckles , the automated task has been failing for reasons as yet unknown at times. I've put this through now and they should be there once indexing happened. I won't close this until that's the case but you should be able to see them there and feel free to close this or ping me if you don't think it's done by 16th June.

**Comment by pwinckles** [comment]
I've published to central before, and I've never seen it take this long. I think something is wrong. Still not there: https://repo1.maven.org/maven2/org/openpreservation/jhove/jhove-core/

**Comment by tledoux** [comment]
Hi Carl, just looking at maven central and still no 1.28 version publish ?!?

**Comment by carlwilson** [comment]
You're not wrong, I'm now suspicious as I closed the staging repository on nexus manually and it reported success. I'll take a closer look at this shortly, grrrrrr....

**Comment by carlwilson** [comment]
So this is fixed now without me really getting to grips with a cause. Sonatype are currently working on a new web front end that handles search and publication and I wonder if this has affected things. We had an identical issue with veraPDF. I simply repeated the same steps as last time, but this time publication seems to have worked: <https://repo1.maven.org/maven2/org/openpreservation/jhove/jhove-core/1.28.0/>
