### ISSUE TITLE
Remove dependency to JAXB

### ISSUE THREAD

**Issue by rsteph-de** [openpreserve/jhove#885]
I am using JHOVE as part of our infrastructure to validate digitized images before publishing them in our institutional repository. During the upgrade of this infrastructure I ran into issues regarding
the transition of [Java EE to Jakarta EE](https://jakarta.ee/blogs/javax-jakartaee-namespace-ecosystem-progress/) which brings us new Java package names and new Maven coordinates for a lot of broadly used Java libraries.

JHOVE has a dependency to the older version the JAXB framework (using the `javax.xml.bind` package name). Since only one small function of this framework is used `(DatatypeConverter.printHexBinary(byte[])`, I suggest to reimplement this function and remove the dependency to JAXB completely.

**Comment by carlwilson** [comment]
Closed by #886
