### ISSUE TITLE
Different element name in UI and when exported as xml or txt - PDF module

### ISSUE THREAD

**Issue by leninoc** [openpreserve/jhove#896]
hi,
I was investigating why PDFMetadata.Images.Image.NisoImageMetadata.MIMEType element in PDF module was not getting any values in Rosetta and found strange differences in xml and txt exports when compared to JHOVE UI.
JHOVE UI result looks like this 
<img width="149" alt="image" src="https://github.com/openpreserve/jhove/assets/10123079/188cfbca-27e5-485c-bb79-0c6a97f29f2e">
MIMEType field with value of "image/jpg".

When exported as xml the (what i think is the same element) is labelled differently. See below:
<img width="474" alt="image" src="https://github.com/openpreserve/jhove/assets/10123079/a3282210-482f-4dd9-a333-17d2462c1ca0">

Similarly in txt output:
<img width="328" alt="image" src="https://github.com/openpreserve/jhove/assets/10123079/5d9272e1-e2c9-4939-b04c-8d11b3325df9">
I think in the xml/txt output is wrong label for MIMEType element. 
thank you
Jan
PDF attached but you can test on any PDF 
[PDFA_in_a_Nutshell_211.pdf](https://github.com/openpreserve/jhove/files/14031828/PDFA_in_a_Nutshell_211.pdf)

**Comment by samalloing** [comment]
Hi Jan,

The XML/Text output is correct according to the [MIX specification](https://groups.niso.org/higherlogic/ws/public/download/17937/ANSI-NISO%20Z39.87-2006%20(R2017)%2C%20Data%20Dictionary%20-%20Technical%20Metadata%20for%20Digital%20Still%20Images.pdf#%5B%7B%22num%22%3A74%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22FitH%22%7D%2C792%5D). The GUI should be changed to FormatName to follow the specifications

Sam

**Comment by leninoc** [comment]
hi Sam,
aha I see now, thanks for pointing it out, I really should have consulted MIX before making any conclusions. From the Note in the formatName description in MIX: "_Values should be taken from a controlled vocabulary. It is permissible to either
list proper format names (e.g., “Adobe PDF”) or MIME types (e.g., “image/tiff”
or “image/jp2”)_" its obvious that it should have never been called MIMEType in JHOVE UI, as MIME type is only one of the possible values.

**So the requested fix should be other way round - rename MIMEType field in UI to FormatName**

cheers
Jan
