### ISSUE TITLE
Example of using jhove within another java application

### ISSUE THREAD

**Issue by johnscancella** [openpreserve/jhove#91]
Hello,

I am working on incorporating jhove into another application, however there doesn't seem to be any documentation on how to do so. Could you please point me to some examples of how to validate the various module types in my own java application?

Thanks

**Comment by johnscancella** [comment]
Also, is there any documentation on creating my own modules or extending current ones? Looking at the code it looks like most of the modules `parse` method is final and thus un extendable.

**Comment by gmcgath** [comment]
I'd plug my book here, but it seems inappropriate. Contact me offline if you like (developer at mcgath dot com).

**Comment by anjackson** [comment]
There's some basic documentation [here](http://jhove.openpreservation.org/documentation/), including notes on [developing a new module](http://jhove.openpreservation.org/documentation/dev-module/). It's old documentation, although I'm pretty sure the JHOVE architecture hasn't changed much. [Documentation pull requests](https://github.com/openpreserve/jhove/tree/gh-pages) are welcome, I'm sure.

The `final` modifiers methods on modules seem like an mistake to me, and should be removed.

Embedding JHOVE appears to mean writing a cut-down version of the [Jhove main class](https://github.com/openpreserve/jhove/blob/integration/jhove-apps/src/main/java/Jhove.java). That's what it says on Gary's [JHOVE Usage Notes](http://www.garymcgath.com/jhovenote.html), which also has a link to the book he's referring to. I've not read it, so can't pass judgement, but it seems you can look through a sample for free.

**Comment by johnscancella** [comment]
Thanks for pointing me to this documentation. Hopefully I will get some time soon to work on a pull request. Right now I am looking through old code where a developer decided it was a good idea to rewrite the JHOVE code without forking it.
