### ISSUE TITLE
JHOVE 1.30 / PDF-hul 1.12.5 reports file as "Well-Formed and valid" despite PDF-HUL-2 error 

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#924]
File to reproduce the issue is avail at https://www.schleswig-holstein.de/DE/landesregierung/ministerien-behoerden/VIII/Service/Broschueren/Broschueren_VIII/Kita/ArbeitshilfenSprachfoerderungElementarbereich.pdf?__blob=publicationFile&v=4 and atached here.

The behavior is as follows:
JHOVE 1.28.0 / PDF-hul 1.12.4 reported the file as "Well-Formed, but not valid" with a PDF-HUL-122 error at Offset 214251
JHOVE 1.30.0 RC1/ PDF-hul 1.12.5 reports the file as "Well-Formed and valid" with a PDF-HUL-2 error and no Offset

Could you advise whether either the PDF-HUL-2 error or the Well-formed and valid error in 1.30 are a false positive?

[ArbeitshilfenSprachfoerderungElementarbereich.pdf](https://github.com/openpreserve/jhove/files/15415535/ArbeitshilfenSprachfoerderungElementarbereich.pdf)

**Comment by samalloing** [comment]
Hi @asciim0,

My bad, I created a pull request for this

Thanks for spotting the mistake

Sam
