### ISSUE TITLE
TIFF-hul, UTF8-hul: update version in pom.xml

### ISSUE THREAD

**Issue by rsteph-de** [openpreserve/jhove#936]
Could you please increase the version numbers for TIFF-hul and UTF8-hul modules.
The latest changes for Jhove 1.30 are not available on Maven Central.
https://central.sonatype.com/artifact/org.openpreservation.jhove.modules/tiff-hul/versions
https://central.sonatype.com/artifact/org.openpreservation.jhove.modules/utf8-hul/versions

XML-hul has been updated:
https://central.sonatype.com/artifact/org.openpreservation.jhove.modules/xml-hul/versions

Maybe the other modules should also be checked for modifications.

**Comment by carlwilson** [comment]
Thanks for reporting this @rsteph-de. PR #951 will fix this, but the publication won't happen until the official 1.32 release in a couple of weeks, if that's OK?
