### ISSUE TITLE
Correct JhoveView version number currently, 1.12.48 (2016-05-12)

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/jhove#94]
Just a minor thing, the JhoveView version number does not seem to be in alignment with the main application:

![image](https://cloud.githubusercontent.com/assets/1880412/16251038/cb416b64-3876-11e6-935f-c4daff7c8b89.png)

**Comment by pmay** [comment]
This seems ok to me - installing from the link on this blog post (http://openpreservation.org/news/jhove-1-14-released/) gave me JhoveView with up to date version (1.14.6 2016-05-12).

However what I found was that the main jhove website points at an old installation file: http://jhove.openpreservation.org/getting-started/#download points at http://downloads.opf-labs.org/dev/jhove-xplt-installer-dev-latest.jar which for me was installing 1.12.48.

**Comment by pmay** [comment]
+1

**Comment by asciim0** [comment]
+1

**Comment by ross-spencer** [comment]
Hi Peter, as you can see our build dates are the same, but I did notice a difference in installer name looking back and somehow I was using something labelled: _jhove-xplt-installer-dev-latest.jar_ I'm not sure what that naming convention is or where that would have been linked from. 

Running from the OPF link above I see the same information as you now: 

![image](https://cloud.githubusercontent.com/assets/1880412/18655421/cb26cd6a-7f3c-11e6-9084-a569a7744b09.png)

**Comment by friesey** [comment]
+1

**Comment by carlwilson** [comment]
No time to do this on the Hack Day as coordinating and testing took priority, returning to the 1.16 fold.

**Comment by carlwilson** [comment]
Yeah, I'm in agreement that it's an installer link thing. Have fixed the website links for now and tested GUI versioning. All seems fine.
