### ISSUE TITLE
Missing offsets with pdf-hul 1.12.6 / problems with backwards compatability of error messages

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#940]
Something appears to have changed between the output from PDF-hul 1.12.4 and PDF-hul 1.12.6. This can pe reproduced using the attached file.

The output with PDF-hul 1.12.4 is:
`Status: Well-Formed, but not valid
  SignatureMatches:
   PDF-hul
  ErrorMessage: Invalid indirect destination - referenced object 'section*.9.6' cannot be found
   ID: PDF-HUL-149
  ErrorMessage: edu.harvard.hul.ois.jhove.module.pdf.PdfInvalidException: Invalid destination object
   ID: PDF-HUL-122
   Offset: 56232
  ErrorMessage: edu.harvard.hul.ois.jhove.module.pdf.PdfInvalidException: Invalid indirect destination - referenced object 'section*.9.6' cannot be found
   ID: PDF-HUL-122
   Offset: 56232`

The output with PDF-hul 1.12.6 is:
`Status: Well-Formed, but not valid
  SignatureMatches:
   PDF-hul
  ErrorMessage: Invalid destination object
   ID: PDF-HUL-1
  ErrorMessage: Invalid indirect destination - referenced object 'section*.9.6' cannot be found
   ID: PDF-HUL-149`

We notice the following differences:
- changed error-IDs: 149 and 2 122 PDF-Hul errors changed to one PDF-HUL-1 and one PDF-HUL-149 --> why is this? release notes should have information on improved rules for error IDs to better interpret this
- missing offsets: PDF-HUL-149 appears to never have had an offset - why is this
- missing known offset: former PDF-HUL-122 with "Invalid indirect destination - referenced object 'section*.9.6" changed to PDF-HUL 149 "Invalid indirect destination - referenced object 'section*.9.6". The error message is the same. If the offset was known when this error was a PDF-HUL-122, the offset should still be known if this error is a PDF-HUL-149. 

My suspicion is that all error messages (the three from 1.12.4 and the two from 1.12.6) describe a singular error that could be captured in one single error messages. Either way, the offset should be included. 

[102_PERC2019_Stein.pdf](https://github.com/user-attachments/files/16612568/102_PERC2019_Stein.pdf)

**Comment by carlwilson** [comment]
OK, I've pinned down the change, it's this PR #882 . The addition is sound as @samalloing points out, but the release details could have been more informative. I agree with the ID change as PDF-HUL-122 is a catch for general exceptions and these are more specific and have extra information. So PDF-HUL-1 and PDF-HUL-149 are existing message codes that are more specific than 122. I also agree that the offset should be there and I'm on that.
