### ISSUE TITLE
jHove 1.32rc German error message shows {0} instead of message

### ISSUE THREAD

**Issue by samalloing** [openpreserve/jhove#954]
Hi @carlwilson 

In the jHove 1.32 RC there is a bug in the XML module that shows instead of the error message an @ sign.
The german version:
![afbeelding](https://github.com/user-attachments/assets/dc21982b-a2fa-46d5-9fde-7dd791b48e57)

The English version:
![afbeelding](https://github.com/user-attachments/assets/f4c64efb-f1a5-4ec9-994e-21ac0ce194e5)
Thanks to Fabian

Sam

**Comment by carlwilson** [comment]
Hi @samalloing, thanks for reporting this. I've fixed the offending string formatter and this will make the 1.32 release without and new RC since it's not risky.
