### ISSUE TITLE
CrossRefStream incorrectly assumes /Index value is a 2 element array

### ISSUE THREAD

**Issue by paulmer** [openpreserve/jhove#96]
The "isValid" method of CrossRefStream is hard coded to assume that an Index element, if present, is an array of exactly 2 integers.  According to the specification, the Index element is "an array containing a pair of integers for each subsection in this section." (http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference15_v6.pdf, page 83 and PDF versions 1.6 and 1.7)  Documents that have more than one subsection fail validation as a result.  PdfModule.readXRefStreams appears to incorporate this assumption and does not validate object numbers against the actual object ranges specified in the index, but instead looks for numbers between 0 and the (meaningless?) value of CrossRefStream.getNumObjects()

**Comment by carlwilson** [comment]
This issue is covered by PR #97 which is weighted 3. Please vote for the PR #97 rather than this issue.
